import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const PORT = 4173;
const server = spawn('npx', ['vite', 'preview', '--port', String(PORT), '--strictPort'], { stdio: 'ignore' });
const wait = (ms) => new Promise(r => setTimeout(r, ms));
await wait(2500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
await p.goto(`http://localhost:${PORT}/simulate` + (process.env.LITE ? '?lite=1' : '')); await wait(5000);
const frame = async () => p.evaluate(() => new Promise(r => { let n = 0; const t0 = performance.now(); function f() { n++; if (n < 15) requestAnimationFrame(f); else r((performance.now() - t0) / n); } requestAnimationFrame(f); }));
console.log('setup frame ms', (await frame()).toFixed(0));
const info = await p.evaluate(() => window.__padworksStats || null);
console.log('info', info);
const tally = await p.evaluate(() => {
  const sc = window.__padworksScene; const out = {};
  const tri = (m) => { const g = m.geometry; if (!g) return 0; const n = g.index ? g.index.count / 3 : g.attributes.position.count / 3; return n * (m.isInstancedMesh ? m.count : 1); };
  const top = (o) => { let x = o; let name = ''; while (x) { if (x.name) name = x.name; x = x.parent; } return name.replace(/-\d+(?=-|$)/g, '') || '(unnamed)'; };
  sc.traverse(o => { if (o.isMesh) { const k = top(o); out[k] = out[k] || { tri: 0, meshes: 0 }; out[k].tri += tri(o); out[k].meshes++; } });
  return Object.entries(out).sort((a, b) => b[1].tri - a[1].tri).slice(0, 25).map(([k, v]) => k + ' ' + Math.round(v.tri) + ' tris / ' + v.meshes + ' meshes').join('\n');
});
console.log(tally);
await p.click('[data-action="start"]', { timeout: 120000 }); await wait(3000);
console.log('rigup frame ms', (await frame()).toFixed(0));
await browser.close(); server.kill();
