// Drop 8 seed: AL (artificial lift: beam unit, rod pump, ESP, gas lift, plunger lift), SC (sand control: gravel
// pack cut-away, screens, liners), and the pad furniture drawn since Drop 7 (containment, sand boxes, fuel gas
// trailers, light towers). Every new record is "draft". Run: node scripts/seed-drop8.mjs
import fs from 'node:fs';
import path from 'node:path';

const DATE = '2026-09-29';
const rev = (note) => ({ rev: 'A', author: 'AI draft', date: DATE, note });
const REC = (sys) => path.resolve('content/records', sys);
const load = (sys, id) => JSON.parse(fs.readFileSync(path.join(REC(sys), id + '.json'), 'utf8'));
const save = (r) => { fs.mkdirSync(REC(r.system), { recursive: true }); fs.writeFileSync(path.join(REC(r.system), r.id + '.json'), JSON.stringify(r, null, 2) + '\n'); };
const H = {
  pressure: { class: 'Stored pressure', control: 'Bleed the tubing and casing to zero and verify before breaking any connection.' },
  pinch: { class: 'Pinch point and rotating equipment', control: 'Lockout the prime mover and brake the unit before anyone approaches the beam, cranks, or belts.' },
  electrical: { class: 'High voltage', control: 'Only qualified people at the drive, transformer, and junction box; lockout before cable work.' },
  gas: { class: 'High-pressure gas', control: 'Injection line rated and restrained; compressor isolated and blown down before work.' },
  lof: { class: 'Line of fire', control: 'Stay clear under the horsehead and beside the bridle; a parted rod string drops the load.' },
  dropped: { class: 'Dropped object', control: 'Certified lifting gear; screens and packers handled with thread protectors and stabbing guides.' },
  h2s: { class: 'H2S', control: 'Monitors at the tree; escape sets staged.' },
  chem: { class: 'Chemicals', control: 'Resin and carrier fluid handling per the data sheets; eye and skin protection.' },
};

// ---- sources
const srcPath = path.resolve('content/sources.json');
const sources = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
const add = (s) => { if (!sources.find(x => x.id === s.id)) sources.push(s); };
add({ id: 'S39', title: 'PetroWiki: Sucker-rod lift (surface unit, rod string, downhole pump, gas anchors)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Sucker-rod_lift' });
add({ id: 'S40', title: 'PetroWiki: Electrical submersible pumps (components, rate range, limits)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Electrical_submersible_pumps' });
add({ id: 'S41', title: 'PetroWiki: Gas lift (continuous and intermittent, plunger note)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Gas_lift' });
add({ id: 'S42', title: 'PetroWiki: Sand control techniques (gravel pack share, screens and liners, consolidation, resin-coated gravel, slot sizing)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Sand_control_techniques' });
add({ id: 'S43', title: 'API Spec 11AX, Subsurface Sucker Rod Pump Assemblies, Components, and Fittings', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S44', title: 'API Spec 11E, Pumping Units', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S45', title: 'API RP 11S series, Electric Submersible Pump installation, operation, and testing', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S46', title: 'API Spec 11V1 and RP 11V5, Gas Lift Valves and Mandrels, and Gas Lift Operations', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S47', title: 'ISO 17824, Sand screens (design, manufacture, and testing)', publisher: 'International Organization for Standardization', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
fs.writeFileSync(srcPath, JSON.stringify(sources, null, 2) + '\n');

// ---- glossary
const gPath = path.resolve('content/glossary.json');
const glossary = JSON.parse(fs.readFileSync(gPath, 'utf8'));
const gadd = (g) => { const i = glossary.findIndex(x => x.term === g.term); if (i >= 0) glossary[i] = g; else glossary.push(g); };
gadd({ term: 'Artificial lift', aliases: ['lift', 'AL', 'rod pump', 'ESP', 'gas lift', 'plunger lift'], system: 'AL', record: 'AL', definition: 'Any method that adds energy to lift fluid from a well that will not flow on its own: a beam unit stroking a rod pump, an electric submersible pump, injected gas, or a plunger.' });
gadd({ term: 'Standing and traveling valves', aliases: ['standing valve', 'traveling valve', 'ball and seat (pump)'], system: 'AL', record: 'AL-RODPUMP', definition: 'The two check valves of a rod pump: the standing valve in the barrel opens on the upstroke to fill it, the traveling valve in the plunger opens on the downstroke so the plunger passes through the fluid it will lift on the next upstroke.' });
gadd({ term: 'Gravel pack', aliases: ['GP', 'cased-hole gravel pack', 'openhole gravel pack', 'frac pack'], system: 'SC', record: 'SC-GRAVELPACK', definition: 'A sand control completion in which sized gravel is packed around a screen so the formation sand bridges on the gravel and the gravel is held by the screen.' });
gadd({ term: 'Wire-wrapped screen', aliases: ['WWS', 'sand screen', 'premium screen', 'slotted liner'], system: 'SC', record: 'SC-GRAVELPACK-SCREEN', definition: 'A base pipe wrapped with keystone wire on ribs, leaving a slot narrower than the gravel or the formation sand it must hold.' });
fs.writeFileSync(gPath, JSON.stringify(glossary, null, 2) + '\n');

// ================================================================ AL system
const EVA = 'PetroWiki sucker-rod lift, ESP, and gas lift pages (S39, S40, S41); API 11AX, 11E, 11S, 11V (S43 to S46); field practice (S9). Generic geometry; not an OEM design.';
const RP_GLB = '/glb/AL/AL-RODPUMP.glb', BU_GLB = '/glb/AL/AL-BEAMUNIT.glb';
const al = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'AL', drawn_in_3d: false, sources: ['S39', 'S9'], revision: rev('Drop 8 seed'), hazards: [H.pressure], ...o });
const alc = (glb) => (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => al({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVA, ...(extra.tabs || {}) }, drawn_in_3d: !!nodes, ...(nodes ? { glb, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });
const rpc = alc(RP_GLB), buc = alc(BU_GLB);

al({ id: 'AL', level: 'system', name: 'Artificial lift', aliases: ['artificial lift', 'lift', 'AL', 'pumping', 'lift method'],
  function: 'The equipment that adds energy to lift fluid once a well will not flow on reservoir pressure alone: beam pumping units with rod pumps, electric submersible pumps, gas lift, and plunger lift, each with its surface and downhole halves.',
  tabs: {
    overview: 'Most shale wells start on natural flow and go on lift within months to a few years as pressure declines and liquids load the tubing. The method is chosen in Pad Setup and appears in the production phase: the beam unit strokes a rod pump at the tubing tail; the ESP hangs a motor and pump on the tubing fed by a cable; gas lift injects compressed gas down the annulus through valves in mandrels; a plunger cycles between a bumper spring and a lubricator on the tree. Rod pumps suit low rates and simple operations, ESPs high rates and deep wells with clean fluid, gas lift sandy or deviated wells with gas available, plunger lift gas wells with modest liquid.',
    engineering: 'Selection follows rate, depth, gas fraction, solids, deviation, power available, and the workover cost of each method. Standards: API 11AX (pumps), 11E (pumping units), 11S (ESP), 11V (gas lift).',
    connections: 'Production tree and tubing head (UC); flowline; power or gas supply; wellhead penetrator or stuffing box at the tree.',
    safety: 'Rotating machinery and the bridle load at the beam unit; high voltage on ESP surface equipment; high-pressure gas on gas lift; a plunger arriving at the lubricator.',
    evidence: EVA, operations: 'Installed with a workover or completion rig after flowback, or later when the well loads up; the ESP and rod pump need the tubing pulled to change.',
    failure_modes: 'Rod parts and pump wear (rod pump); motor burn, cable damage, and gas or sand lock (ESP); valve leaks and compressor outages (gas lift); plunger sticking or fast arrivals (plunger).',
  }, standards: [{ standard: 'API Spec 11AX', edition: 'verify', paraphrase: 'Subsurface pump assemblies and components.', source: 'S43' }, { standard: 'API Spec 11E', edition: 'verify', paraphrase: 'Pumping unit design and rating.', source: 'S44' }, { standard: 'API RP 11S', edition: 'verify', paraphrase: 'ESP installation, operation, and testing practices.', source: 'S45' }, { standard: 'API Spec 11V1', edition: 'verify', paraphrase: 'Gas lift valves and mandrels.', source: 'S46' }],
  hazards: [H.pinch, H.electrical, H.gas, H.lof], sources: ['S39', 'S40', 'S41', 'S43', 'S44', 'S45', 'S46', 'S9'] });

al({ id: 'AL-BEAMUNIT', parent: 'AL', group: 'rod-lift', level: 'equipment', name: 'Beam pumping unit (conventional)', aliases: ['beam pumping unit', 'pumpjack', 'beam unit', 'horsehead pump', 'nodding donkey'],
  function: 'The surface machine of rod lift: a prime mover turns a gear reducer whose cranks rock a walking beam on a Samson post, so the horsehead lifts and lowers the polished rod and the rod string below it.',
  tabs: {
    overview: 'Base to horsehead: a skid base, the Samson post carrying the center bearing, the walking beam with the horsehead at the well end and the equalizer at the tail, two pitman arms from the equalizer down to the crank pins, two cranks with counterweights on the slow shaft of the gear reducer, the prime mover (electric motor or gas engine) driving the reducer through V-belts under a guard, and the bridle from the horsehead to the polished rod clamp. The polished rod runs through a stuffing box on the pumping tee at the tree. Counterweights balance the rod load so the motor works evenly on both strokes. The model is shown mid-upstroke and the simulator animates the crank, beam, and rod.',
    engineering: 'Rated by API 11E designation (reducer torque, structure load, stroke length). Stroke length and strokes per minute set the displacement with the pump bore; the counterbalance is set from dynamometer cards.',
    connections: 'Polished rod to the rod string; stuffing box on the pumping tee (UC tree); power to the prime mover; flowline from the tee.',
    safety: 'Rotating cranks and counterweights, the belt drive, and the beam sweep are the pinch and line-of-fire zones; brake and lockout before anyone approaches; a parted rod string drops the bridle load.',
    evidence: EVA, operations: 'Set on a foundation over the well, aligned to the polished rod, balanced, then run on a timer or a pump-off controller.',
    failure_modes: 'Structural bearing wear, reducer gear damage from imbalance, belt failures, stuffing box leaks, polished rod breaks.',
  }, drawn_in_3d: true, glb: BU_GLB, scene: 'AL-BEAMUNIT',
  mesh_nodes: ['AL-BEAMUNIT-BASE', 'AL-BEAMUNIT-SAMSONPOST', 'AL-BEAMUNIT-WALKINGBEAM', 'AL-BEAMUNIT-HORSEHEAD', 'AL-BEAMUNIT-EQUALIZER', 'AL-BEAMUNIT-PITMAN', 'AL-BEAMUNIT-CRANK', 'AL-BEAMUNIT-COUNTERWEIGHT', 'AL-BEAMUNIT-GEARREDUCER', 'AL-BEAMUNIT-PRIMEMOVER', 'AL-BEAMUNIT-BELTGUARD', 'AL-BEAMUNIT-BRIDLE', 'AL-BEAMUNIT-POLISHEDROD', 'AL-BEAMUNIT-STUFFINGBOX', 'AL-BEAMUNIT-WELLHEAD'],
  standards: [{ standard: 'API Spec 11E', edition: 'verify', paraphrase: 'Pumping unit structure, reducer rating, and testing.', source: 'S44' }], sources: ['S39', 'S44', 'S9'], hazards: [H.pinch, H.lof],
  connections: [{ target: 'AL-RODPUMP', direction: 'downstream', type: 'mechanical', note: 'through the rod string' }, { target: 'UC-PRODTREE', direction: 'downstream', type: 'threaded', note: 'stuffing box on the pumping tee' }] });
buc('AL-BEAMUNIT-BASE', 'AL-BEAMUNIT', 'rod-lift', 'Base and foundation', ['unit base', 'skid (pumping unit)'], 'The steel skid that carries the Samson post, reducer, and prime mover and bolts to the concrete or timber foundation.', 'Sets the geometry of the unit; leveled and anchored so the polished rod stays centered in the stuffing box.', 'Per API 11E; foundation per the unit size and soil.', 'Anchor bolts checked; no one on the base while running.', ['AL-BEAMUNIT-BASE']);
buc('AL-BEAMUNIT-SAMSONPOST', 'AL-BEAMUNIT', 'rod-lift', 'Samson post and center bearing', ['Samson post', 'A-frame', 'center bearing'], 'The A-frame that carries the walking beam on the center bearing, taking the whole rod load plus the counterbalance.', 'Three legs to a saddle bearing; the beam pivots here so the horsehead end and the tail end move opposite ways.', 'Structure rating per API 11E.', 'Ladder access only with the unit braked.', ['AL-BEAMUNIT-SAMSONPOST']);
buc('AL-BEAMUNIT-WALKINGBEAM', 'AL-BEAMUNIT', 'rod-lift', 'Walking beam', ['beam', 'walking beam'], 'The lever pivoting on the center bearing: the horsehead at the well end, the equalizer bearing at the tail.', 'Class I lever on a conventional unit; the stroke at the horsehead follows the crank radius through the pitman geometry.', 'Structural rating per API 11E.', 'Beam sweep is the line of fire.', ['AL-BEAMUNIT-WALKINGBEAM']);
buc('AL-BEAMUNIT-HORSEHEAD', 'AL-BEAMUNIT', 'rod-lift', 'Horsehead', ['horsehead', 'horse head'], 'The curved head at the well end of the beam whose arc keeps the bridle vertical over the well through the stroke.', 'The arc is centered on the beam pivot so the polished rod moves straight up and down; it is removable to let a rig over the well.', 'Per the unit size.', 'Removed or swung aside with the unit braked before a workover.', ['AL-BEAMUNIT-HORSEHEAD']);
buc('AL-BEAMUNIT-EQUALIZER', 'AL-BEAMUNIT', 'rod-lift', 'Equalizer and tail bearing', ['equalizer', 'tail bearing'], 'The cross member at the tail of the beam that shares the pitman loads between the two arms.', 'Bearing on the beam; the pitman side members hang from its ends.', 'Per API 11E.', 'Greased on schedule.', ['AL-BEAMUNIT-EQUALIZER']);
buc('AL-BEAMUNIT-PITMAN', 'AL-BEAMUNIT', 'rod-lift', 'Pitman arms', ['pitman', 'pitman arm', 'connecting rods'], 'The two arms from the equalizer down to the crank pins that turn crank rotation into beam rocking.', 'Wrist pins at the crank end; the arm length and crank radius set the stroke.', 'Per API 11E.', 'Rotating linkage; guarded zone.', ['AL-BEAMUNIT-PITMAN']);
buc('AL-BEAMUNIT-CRANK', 'AL-BEAMUNIT', 'rod-lift', 'Cranks', ['crank', 'crank arm'], 'The two arms on the reducer slow shaft carrying the crank pins and the counterweights.', 'Several pin positions give several stroke lengths.', 'Per API 11E.', 'Rotating; the brake holds them for maintenance.', ['AL-BEAMUNIT-CRANK']);
buc('AL-BEAMUNIT-COUNTERWEIGHT', 'AL-BEAMUNIT', 'rod-lift', 'Counterweights', ['counterweight', 'counterbalance'], 'Cast weights on the cranks positioned so the unit lifts the rod string and fluid on the upstroke with the same torque it lifts the weights on the downstroke.', 'Moved along the crank to balance; checked with a dynamometer or motor current.', 'Per API 11E torque rating.', 'Heavy rotating mass; never adjusted without the brake set and the cranks chocked.', ['AL-BEAMUNIT-COUNTERWEIGHT'], { hazards: [H.pinch] });
buc('AL-BEAMUNIT-GEARREDUCER', 'AL-BEAMUNIT', 'rod-lift', 'Gear reducer', ['gear reducer', 'speed reducer', 'reducer'], 'The double-reduction gearbox that turns the prime mover speed into a few strokes per minute at the crank shaft.', 'Rated by peak torque in API 11E; oil bath lubrication.', 'API 11E.', 'Oil level and leaks checked; overload from imbalance shows as gear damage.', ['AL-BEAMUNIT-GEARREDUCER']);
buc('AL-BEAMUNIT-PRIMEMOVER', 'AL-BEAMUNIT', 'rod-lift', 'Prime mover and belt guard', ['prime mover (pumping unit)', 'motor (pumping unit)', 'gas engine', 'belt guard'], 'The electric motor or gas engine that drives the reducer through V-belts under a guard.', 'NEMA D motors with high slip are common; a variable speed drive or a pump-off controller cycles the unit.', 'Sized to the peak torque with the counterbalance set.', 'Belts and sheaves guarded; lockout before belt work.', ['AL-BEAMUNIT-PRIMEMOVER', 'AL-BEAMUNIT-BELTGUARD'], { hazards: [H.pinch, H.electrical] });
buc('AL-BEAMUNIT-BRIDLE', 'AL-BEAMUNIT', 'rod-lift', 'Bridle and carrier bar', ['bridle', 'wireline hanger', 'carrier bar'], 'The pair of wire ropes from the horsehead to the carrier bar that hangs the polished rod clamp.', 'Follows the horsehead arc so the rod stays vertical.', 'Rated above the peak polished rod load.', 'Never under the carrier bar while the unit runs.', ['AL-BEAMUNIT-BRIDLE'], { hazards: [H.lof] });
buc('AL-BEAMUNIT-POLISHEDROD', 'AL-BEAMUNIT', 'rod-lift', 'Polished rod and clamp', ['polished rod', 'rod clamp'], 'The smooth rod at the top of the rod string that reciprocates through the stuffing box, clamped to the carrier bar.', 'Hardened, polished surface for the packing; the clamp sets the spacing of the pump.', 'Per API 11B rod practice.', 'Clamp torque and rod wear inspected.', ['AL-BEAMUNIT-POLISHEDROD']);
buc('AL-BEAMUNIT-STUFFINGBOX', 'AL-BEAMUNIT', 'rod-lift', 'Stuffing box and pumping tee', ['stuffing box (rod lift)', 'pumping tee', 'rod BOP'], 'The packing gland on the pumping tee that seals around the moving polished rod while production leaves through the tee side outlet.', 'Packing tightened as it wears; a rod BOP below it isolates the well for packing changes.', 'Rated with the tree.', 'Leak is the first sign of packing wear; bled through the tee before service.', ['AL-BEAMUNIT-STUFFINGBOX', 'AL-BEAMUNIT-WELLHEAD'], { hazards: [H.pressure, H.h2s] });

al({ id: 'AL-RODSTRING', parent: 'AL', group: 'rod-lift', level: 'equipment', name: 'Sucker rod string', aliases: ['sucker rods', 'rod string', 'rods', 'fiberglass rods'],
  function: 'The string of steel (or fiberglass) rods, 25 or 30 ft long, coupled from the polished rod down to the pump plunger, carrying the pump load through the tubing.',
  tabs: { overview: 'Rods from 5/8 to 1-1/4 in. in a tapered string, heavier at the top where the load is highest; rod guides where the tubing curves; a sinker bar above the pump to keep the string in tension on the downstroke.', engineering: 'Taper design per API 11B; stretch and load from the pump depth, fluid, and stroke.', safety: 'Rod parts drop the bridle load; fished with the rig.', evidence: EVA, failure_modes: 'Fatigue parts at couplings, wear against the tubing in the curve, corrosion pitting.' }, sources: ['S39', 'S9'] });
al({ id: 'AL-RODPUMP', parent: 'AL', group: 'rod-lift', level: 'equipment', name: 'Rod pump (insert pump, cut-away)', aliases: ['rod pump', 'subsurface pump', 'insert pump', 'bottomhole pump', 'sucker rod pump'],
  function: 'The positive-displacement pump at the tubing tail, stroked by the rod string: a plunger in a barrel with a traveling valve in the plunger and a standing valve in the barrel.',
  tabs: {
    overview: 'The insert pump is run on the rods and seats in a seating nipple in the tubing on a hold-down. Upstroke: the traveling valve closes and the plunger lifts the fluid above it while the standing valve opens and the barrel fills from below. Downstroke: the standing valve closes and the traveling valve opens as the plunger passes down through the fluid. A gas anchor below the intake separates free gas so the pump fills with liquid. The cut-away shows the barrel, plunger mid-stroke, both ball-and-seat valves in their cages, the valve rod and coupling, the hold-down and seating nipple, and the gas anchor, with the tubing as ghost context.',
    engineering: 'API 11AX designations name bore, barrel and plunger type, and seating. Displacement is bore area times stroke times strokes per minute less slippage; deep wells use smaller bores to limit rod load.',
    connections: 'Rod string above; seating nipple in the tubing (UC); gas anchor below.',
    safety: 'Pulled with the rods on a rig; the well is killed or the tubing isolated first.',
    evidence: EVA, operations: 'Spaced so the plunger does not tag the standing valve; monitored by dynamometer.',
    failure_modes: 'Valve leaks (worn balls and seats), plunger and barrel wear from sand, gas lock, stuck plunger.',
  }, drawn_in_3d: true, glb: RP_GLB, scene: 'AL-RODPUMP',
  mesh_nodes: ['AL-RODPUMP-SEATINGNIPPLE', 'AL-RODPUMP-HOLDDOWN', 'AL-RODPUMP-BARREL', 'AL-RODPUMP-STANDINGVALVE', 'AL-RODPUMP-STANDINGBALL', 'AL-RODPUMP-PLUNGER', 'AL-RODPUMP-TRAVELINGVALVE', 'AL-RODPUMP-TRAVELINGBALL', 'AL-RODPUMP-VALVEROD', 'AL-RODPUMP-RODCOUPLING', 'AL-RODPUMP-GASANCHOR'],
  ghost_nodes: ['AL-RODPUMP-TUBING'],
  standards: [{ standard: 'API Spec 11AX', edition: 'verify', paraphrase: 'Subsurface pump assemblies, components, and fittings.', source: 'S43' }], sources: ['S39', 'S43', 'S9'] });
rpc('AL-RODPUMP-BARREL', 'AL-RODPUMP', 'rod-lift', 'Pump barrel', ['barrel', 'pump barrel'], 'The honed tube the plunger strokes in; its bore sets the pump displacement.', 'Heavy-wall or thin-wall barrel per API 11AX; chrome or nickel plated bores for sand.', 'API 11AX.', 'Pulled with the pump.', ['AL-RODPUMP-BARREL']);
rpc('AL-RODPUMP-PLUNGER', 'AL-RODPUMP', 'rod-lift', 'Plunger', ['pump plunger', 'plunger (rod pump)'], 'The close-fit piston stroked by the rods, carrying the traveling valve at its bottom; the clearance to the barrel sets slippage.', 'Metal plungers with grooves to trap sand, or soft-packed plungers; fit chosen for the fluid viscosity.', 'API 11AX fits.', 'Wear shows as falling pump efficiency.', ['AL-RODPUMP-PLUNGER']);
rpc('AL-RODPUMP-TRAVELINGVALVE', 'AL-RODPUMP', 'rod-lift', 'Traveling valve', ['traveling valve', 'TV'], 'The ball and seat in a cage at the bottom of the plunger: closed on the upstroke to lift the fluid, open on the downstroke.', 'Ball and seat in hard alloys; the cage guides the ball.', 'API 11AX.', 'A leaking traveling valve shows on the dynamometer card.', ['AL-RODPUMP-TRAVELINGVALVE', 'AL-RODPUMP-TRAVELINGBALL']);
rpc('AL-RODPUMP-STANDINGVALVE', 'AL-RODPUMP', 'rod-lift', 'Standing valve', ['standing valve', 'SV'], 'The ball and seat in a cage at the bottom of the barrel: open on the upstroke to fill the barrel, closed on the downstroke to hold the column.', 'Same ball-and-seat family as the traveling valve; retrievable with the pump.', 'API 11AX.', 'A leaking standing valve lets the column fall back on the downstroke.', ['AL-RODPUMP-STANDINGVALVE', 'AL-RODPUMP-STANDINGBALL']);
rpc('AL-RODPUMP-SEATINGNIPPLE', 'AL-RODPUMP', 'rod-lift', 'Seating nipple and hold-down', ['seating nipple', 'hold-down', 'mechanical hold-down', 'cup hold-down'], 'The profile in the tubing that the pump seats in and the hold-down (cups or a mechanical lock) that keeps it there against the pumping load.', 'Top or bottom hold-down per the pump designation; the nipple is run with the tubing.', 'API 11AX.', 'The pump is unseated by picking up the rods before pulling.', ['AL-RODPUMP-SEATINGNIPPLE', 'AL-RODPUMP-HOLDDOWN']);
rpc('AL-RODPUMP-VALVEROD', 'AL-RODPUMP', 'rod-lift', 'Valve rod and rod coupling', ['valve rod', 'pull tube', 'pump coupling'], 'The rod from the plunger up through the barrel top to the coupling on the first sucker rod.', 'Guided at the barrel top; a pull tube replaces it on some designs.', 'API 11AX.', 'Wear at the guide.', ['AL-RODPUMP-VALVEROD', 'AL-RODPUMP-RODCOUPLING']);
rpc('AL-RODPUMP-GASANCHOR', 'AL-RODPUMP', 'rod-lift', 'Gas anchor', ['gas anchor', 'gas separator (rod pump)', 'poor boy anchor', 'mud anchor', 'dip tube'], 'The downhole separator below the pump intake: fluid enters an outer mud anchor, gas breaks out upward, and liquid is drawn through a dip tube into the pump.', 'Natural or poor-boy designs; sized so the downward liquid velocity is below the bubble rise velocity.', 'Per the well gas fraction.', 'Undersized anchors gas-lock the pump.', ['AL-RODPUMP-GASANCHOR'], { tabs: { evidence: 'Gas separator types per PetroWiki sucker-rod lift (S39).' } });
al({ id: 'AL-RODPUMP-TUBINGREF', parent: 'AL-RODPUMP', group: 'rod-lift', level: 'component', name: 'Tubing around the pump (context)', aliases: ['tubing (pump context)'], function: 'The production tubing the pump seats in, shown translucent for context.', tabs: { overview: 'Ghost context in the cut-away; the seating nipple is part of the tubing string.', engineering: 'See UC-TUBING.', safety: 'None beyond the tubing.', evidence: EVA }, drawn_in_3d: true, glb: RP_GLB, mesh_nodes: ['AL-RODPUMP-TUBING'], connections: [{ target: 'UC-TUBING', direction: 'undirected', type: 'threaded' }] });

al({ id: 'AL-ESP', parent: 'AL', group: 'esp', level: 'equipment', name: 'Electric submersible pump system', aliases: ['ESP', 'submersible pump', 'electric submersible pump', 'ESP system'],
  function: 'A multistage centrifugal pump driven by a downhole electric motor on the tubing tail, powered through a cable from a drive at surface: the high-rate lift method.',
  tabs: {
    overview: 'Bottom to top: the motor (three-phase induction), the seal or protector section that isolates motor oil from well fluid and takes the thrust, the intake or gas separator, the multistage pump, and the discharge into the tubing. A flat cable runs up the tubing under clamps to a wellhead penetrator, then to a junction box, the variable speed drive, and a transformer at surface. Rates from a few hundred to more than a hundred thousand barrels per day; the simulator draws the drive and transformer skid, the junction box, and the cable at the tree, and the motor, seal, intake, and pump on the tubing downhole.',
    engineering: 'Needs casing larger than about 4-1/2 in.; efficiency drops below a few hundred barrels per day; sensitive to sand and free gas; sized from the inflow and the tubing head pressure; run per API RP 11S.',
    connections: 'Tubing (UC); cable and penetrator at the tubing hanger; power from the pad or the grid.',
    safety: 'Medium-voltage cable and drive; lockout before any cable, penetrator, or drive work.',
    evidence: EVA, operations: 'Run with the tubing on a rig; started and ramped on the drive; watched on downhole sensor data.',
    failure_modes: 'Motor burn from overheating or low flow, cable damage during running, gas lock, sand wear of stages, seal failure.',
  }, drawn_in_3d: true, scene: 'AL-ESP', standards: [{ standard: 'API RP 11S', edition: 'verify', paraphrase: 'ESP installation, operation, and testing.', source: 'S45' }], sources: ['S40', 'S45', 'S9'], hazards: [H.electrical, H.pressure] });
al({ id: 'AL-ESP-MOTOR', parent: 'AL-ESP', group: 'esp', level: 'component', name: 'Motor and seal section', aliases: ['ESP motor', 'protector', 'seal section'], function: 'The oil-filled three-phase motor at the bottom of the assembly and the seal section above it that equalizes pressure, isolates the motor oil, and carries the pump thrust.', tabs: { overview: 'Long, small-diameter motor cooled by the fluid flowing past it to the intake; the seal chambers use bags or labyrinths.', engineering: 'Voltage and horsepower per the pump; sensor package below the motor.', safety: 'Medium voltage.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-ESP', sources: ['S40', 'S9'], hazards: [H.electrical] });
al({ id: 'AL-ESP-PUMP', parent: 'AL-ESP', group: 'esp', level: 'component', name: 'Intake, gas separator, and pump stages', aliases: ['ESP pump', 'pump stages', 'gas separator (ESP)', 'ESP intake'], function: 'The intake or rotary gas separator and the stack of impeller and diffuser stages that build the head.', tabs: { overview: 'Each stage adds a head; stage count and type set the rate and pressure; abrasion-resistant stages for sand.', engineering: 'Selected on the pump curve at the drive frequency.', safety: 'None beyond the assembly.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-ESP', sources: ['S40'] });
al({ id: 'AL-ESP-CABLE', parent: 'AL-ESP', group: 'esp', level: 'component', name: 'Power cable and wellhead penetrator', aliases: ['ESP cable', 'flat cable', 'penetrator', 'cable clamps'], function: 'The three-phase cable banded to the tubing from the motor to the wellhead penetrator that carries it through the tubing hanger.', tabs: { overview: 'Round cable in the vertical, flat cable across the pump; clamps every joint; the penetrator seals the conductors through the hanger.', engineering: 'Rated for the temperature and gas; voltage drop over the length.', safety: 'Medium voltage; damaged on running if the clamps are missed.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-ESP-PENETRATOR', sources: ['S40', 'S45'], hazards: [H.electrical] });
al({ id: 'AL-ESP-VSD', parent: 'AL-ESP', group: 'esp', level: 'component', name: 'Variable speed drive, transformer, and junction box', aliases: ['VSD', 'ESP drive', 'switchboard', 'step-up transformer', 'junction box'], function: 'The surface electrical package: the drive that sets the motor frequency, the transformer that steps its output to the motor voltage, and the vented junction box where the well cable meets the surface cable.', tabs: { overview: 'The drive starts the motor softly and trims the rate; the junction box vents gas that migrates up the cable so it never reaches the drive.', engineering: 'Drive sized to the motor current; transformer to the cable voltage.', safety: 'High voltage; the junction box is never sealed.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-ESP-VSD', sources: ['S40', 'S45'], hazards: [H.electrical] });

al({ id: 'AL-GASLIFT', parent: 'AL', group: 'gas-lift', level: 'equipment', name: 'Gas lift system', aliases: ['gas lift', 'GL', 'continuous gas lift', 'intermittent gas lift'],
  function: 'Compressed gas injected down the casing annulus and into the tubing through valves in side pocket mandrels, lightening the fluid column so the well flows.',
  tabs: {
    overview: 'Continuous gas lift injects steadily to cut the tubing fluid density, the common mode for higher rates; intermittent lift injects slugs of gas to displace liquid, for low rates. Unloading valves at several depths open in sequence from the top as the annulus is unloaded, then close, leaving injection through the deepest operating valve or orifice. Surface: a compressor (or a central gas lift system), the injection line with a choke and meter, and the casing side outlet at the tree. The simulator draws the compressor skid and injection line and the mandrels on the tubing.',
    engineering: 'Valves per API 11V1; design and operations per API RP 11V5; the compressor is the expensive element.',
    connections: 'Casing side outlet on the wellhead (WH); tubing mandrels (UC); gas supply.',
    safety: 'High-pressure gas at the line and compressor; fuel gas leaks.',
    evidence: EVA, operations: 'Unloaded stage by stage; the injection rate tuned to the well.',
    failure_modes: 'Valve leaks or failures to close, compressor outages, hydrates in the line, tubing-casing communication.',
  }, drawn_in_3d: true, scene: 'AL-GASLIFT', standards: [{ standard: 'API Spec 11V1', edition: 'verify', paraphrase: 'Gas lift valves, orifices, reverse flow valves, and dummy valves.', source: 'S46' }], sources: ['S41', 'S46', 'S9'], hazards: [H.gas] });
al({ id: 'AL-GASLIFT-MANDREL', parent: 'AL-GASLIFT', group: 'gas-lift', level: 'component', name: 'Side pocket mandrel and gas lift valve', aliases: ['side pocket mandrel', 'SPM', 'gas lift valve', 'unloading valve', 'orifice valve'], function: 'The tubing sub with an offset pocket that holds a wireline-retrievable gas lift valve; the valve opens to let annulus gas into the tubing.', tabs: { overview: 'Several mandrels down the string; unloading valves above, the operating valve or orifice at the deepest point of injection; valves are pulled and set with slickline kickover tools.', engineering: 'Valve set pressures staged for the unloading sequence.', safety: 'Slickline work through the tree lubricator.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-GASLIFT', sources: ['S41', 'S46'] });
al({ id: 'AL-GASLIFT-COMPRESSOR', parent: 'AL-GASLIFT', group: 'gas-lift', level: 'component', name: 'Compressor and injection line', aliases: ['gas lift compressor', 'injection line', 'lift gas meter'], function: 'The wellsite compressor (or the tie-in to a central system) and the metered injection line to the casing side outlet.', tabs: { overview: 'Gas engine or electric compressor with a cooler; the injection choke and meter set the rate per well.', engineering: 'Discharge pressure above the deepest valve opening pressure plus line losses.', safety: 'High-pressure gas; blowdown before work.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-GASLIFT-COMPRESSOR', sources: ['S41', 'S9'], hazards: [H.gas] });

al({ id: 'AL-PLUNGERLIFT', parent: 'AL', group: 'plunger-lift', level: 'equipment', name: 'Plunger lift', aliases: ['plunger lift', 'free piston lift', 'plunger (lift)'],
  function: 'A free piston that falls to a bumper spring at the tubing tail while the well is shut in, then rides the gas back to a lubricator on the tree, sweeping the liquid ahead of it.',
  tabs: {
    overview: 'A controller on a post cycles the motor valve on the flowline: shut in to build pressure, open to bring the plunger up with its liquid slug, flow, then shut in again as the plunger falls. An arrival sensor on the lubricator times each cycle. Uses the well\'s own gas, no pump, few moving parts; suited to gas wells with modest liquid. The simulator draws the lubricator on the tree, the controller, and the plunger cycling in the tubing.',
    engineering: 'Needs enough gas-liquid ratio and shut-in pressure to lift the slug; plunger types (solid, pad, bypass) for fall speed and seal.',
    connections: 'Tree cap replaced by the lubricator (UC); flowline motor valve; bumper spring in the tubing tail.',
    safety: 'A fast arrival hammers the lubricator; the catcher and arrival sensor limit that; the lubricator is a pressure vessel at tubing pressure.',
    evidence: EVA, operations: 'Cycle tuned from arrival times and casing pressure.',
    failure_modes: 'Plunger sticking, worn plungers that will not seal, fast arrivals, controller valve leaks.',
  }, drawn_in_3d: true, scene: 'AL-PLUNGERLIFT', sources: ['S41', 'S9'], hazards: [H.pressure, H.lof] });
al({ id: 'AL-PLUNGERLIFT-LUBRICATOR', parent: 'AL-PLUNGERLIFT', group: 'plunger-lift', level: 'component', name: 'Plunger lubricator and catcher', aliases: ['lubricator (plunger)', 'plunger catcher', 'arrival sensor'], function: 'The housing on the tree cap that receives the plunger, with a spring or catcher, an arrival sensor, and a cap for changing the plunger.', tabs: { overview: 'The plunger stops here on each arrival; the catcher holds it for inspection; the sensor tells the controller it arrived.', engineering: 'Rated to the tree.', safety: 'Bled through the cap valve before opening.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-PLUNGERLIFT-LUBRICATOR', sources: ['S41', 'S9'], hazards: [H.pressure] });
al({ id: 'AL-PLUNGERLIFT-CONTROLLER', parent: 'AL-PLUNGERLIFT', group: 'plunger-lift', level: 'component', name: 'Controller and motor valve', aliases: ['plunger controller', 'motor valve', 'solar controller'], function: 'The solar-powered controller that opens and closes the flowline motor valve on time or pressure to cycle the plunger.', tabs: { overview: 'Reads casing and tubing pressure and the arrival sensor; adjusts shut-in and flow times.', engineering: 'Pneumatic or electric motor valve on the flowline.', safety: 'Low voltage; flowline pressure at the valve.', evidence: EVA }, drawn_in_3d: true, scene: 'AL-PLUNGERLIFT-CONTROLLER', sources: ['S41'] });

// ================================================================ SC system
const EVS = 'PetroWiki sand control techniques (S42), ISO 17824 for screens (S47), API RP 19C for gravel testing (S12 if held), field practice (S9). Generic geometry; not an OEM design.';
const GP_GLB = '/glb/SC/SC-GRAVELPACK.glb';
const sc = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'SC', drawn_in_3d: false, sources: ['S42', 'S9'], revision: rev('Drop 8 seed'), hazards: [H.pressure], ...o });
const scc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => sc({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVS, ...(extra.tabs || {}) }, drawn_in_3d: !!nodes, ...(nodes ? { glb: GP_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

sc({ id: 'SC', level: 'system', name: 'Sand control', aliases: ['sand control', 'SC', 'sand screens', 'sand exclusion'],
  function: 'The completions that keep formation sand out of the wellbore in weak formations: gravel packs around screens, standalone screens and slotted liners, frac packs, and chemical consolidation.',
  tabs: {
    overview: 'Shale wells rarely need downhole sand control; their sand problem is proppant flowback handled at surface (FB). Weak sandstone reservoirs, offshore and in many conventional fields, do: the standard answer is a gravel pack, which public sources put at more than 90 percent of sand control completions. A screen is run across the interval and sized gravel is pumped into the annulus so the formation sand bridges on the gravel and the gravel is held by the screen. Frac packs combine a short fracture with a gravel pack; standalone screens rely on the formation sand bridging on the screen itself; resin consolidation glues the sand grains in place.',
    engineering: 'Gravel sized from the formation sand distribution; screen slot narrower than the gravel; screens designed and tested to ISO 17824. Screens or liners without gravel plug over time in most formations.',
    connections: 'Casing and perforations (CM, WL); production packer and tubing above (UC); the gravel pack service tools on the workstring (RG).',
    safety: 'Pumping pressures during the pack; heavy screen assemblies handled with the rig.',
    evidence: EVS, operations: 'Perforate, clean out, run the screen assembly with the gravel pack packer, set, pump the pack through the crossover, reverse out, pull the service tool, run the completion.',
    failure_modes: 'Screen erosion or plugging, incomplete packs leaving voids, packer or seal leaks, sand production returning.',
  }, standards: [{ standard: 'ISO 17824', edition: 'verify', paraphrase: 'Sand screen design, manufacture, and testing.', source: 'S47' }], hazards: [H.pressure, H.dropped], sources: ['S42', 'S47', 'S9'] });
sc({ id: 'SC-GRAVELPACK', parent: 'SC', group: 'gravel-pack', level: 'equipment', name: 'Cased-hole gravel pack (cut-away)', aliases: ['gravel pack', 'GP', 'cased-hole gravel pack', 'gravel pack completion', 'frac pack'],
  function: 'The screen assembly and gravel placed across a perforated interval so sand cannot enter the wellbore: gravel pack packer and crossover above, blank pipe, screen on a perforated base pipe, gravel in the annulus and perforations, sump packer and seal assembly below.',
  tabs: {
    overview: 'The sump packer is set below the interval first. The screen assembly runs on the gravel pack packer with the crossover tool and washpipe inside; the packer sets, the crossover ports open, and gravel slurry is pumped down the workstring, out through the crossover into the annulus around the screen, packing the perforations and the annulus while the carrier fluid returns through the screen and up the washpipe. The service tool and washpipe come out; the seal assembly of the completion stabs into the packer. The cut-away shows every element with the casing, cement, and formation as ghost context; a frac pack uses the same hardware with a short fracture pumped first.',
    engineering: 'Gravel sized about six times the formation sand median (a widely used rule); screen slot narrower than the smallest gravel; pack quality logged with density tools.',
    connections: 'Casing and perforations (CM, WL); production packer and tubing above (UC); workstring during the pack (RG).',
    safety: 'Pack pumped at rate and pressure against the packer; heavy assembly on the rig.',
    evidence: EVS, operations: 'Sump packer, clean-out, screen run, set, pack, reverse, pull, complete.',
    failure_modes: 'Voids from premature screenout, screen damage on running, packer leaks, fines plugging the pack.',
  }, drawn_in_3d: true, glb: GP_GLB, scene: 'SC-GRAVELPACK',
  mesh_nodes: ['SC-GRAVELPACK-GPPACKER', 'SC-GRAVELPACK-CROSSOVER', 'SC-GRAVELPACK-BLANKPIPE', 'SC-GRAVELPACK-SCREEN', 'SC-GRAVELPACK-BASEPIPE', 'SC-GRAVELPACK-GRAVEL', 'SC-GRAVELPACK-SUMPPACKER', 'SC-GRAVELPACK-SEALASSEMBLY'],
  ghost_nodes: ['SC-GRAVELPACK-CASING', 'SC-GRAVELPACK-FORMATION', 'SC-GRAVELPACK-WASHPIPE'], sources: ['S42', 'S47', 'S9'] });
scc('SC-GRAVELPACK-GPPACKER', 'SC-GRAVELPACK', 'gravel-pack', 'Gravel pack packer', ['GP packer', 'gravel pack packer', 'top packer'], 'The packer above the interval that carries the screen assembly, seals the annulus, and receives the completion seal assembly afterwards.', 'Set hydraulically from the service tool; its bore takes the crossover during the pack and the production seals after.', 'Rated for the pack pressure and the production differential.', 'Set and tested before the pack is pumped.', ['SC-GRAVELPACK-GPPACKER']);
scc('SC-GRAVELPACK-CROSSOVER', 'SC-GRAVELPACK', 'gravel-pack', 'Crossover tool and ports', ['crossover', 'crossover tool', 'service tool', 'gravel pack ports'], 'The service tool below the packer that routes slurry from the workstring out to the annulus and returns from the washpipe back up the workstring-casing annulus.', 'Positions: squeeze, circulate, reverse; shifted by picking up and setting down the workstring.', 'Per the service company tool.', 'Pressure test in each position before the pack.', ['SC-GRAVELPACK-CROSSOVER']);
scc('SC-GRAVELPACK-BLANKPIPE', 'SC-GRAVELPACK', 'gravel-pack', 'Blank pipe', ['blank', 'blank pipe', 'gravel reserve'], 'The unperforated pipe between the crossover and the screen that holds a reserve of gravel above the screen for settling.', 'Length set so the pack top stays above the screen.', 'Casing-grade pipe.', 'None beyond the string.', ['SC-GRAVELPACK-BLANKPIPE']);
scc('SC-GRAVELPACK-SCREEN', 'SC-GRAVELPACK', 'gravel-pack', 'Wire-wrapped screen', ['screen', 'wire-wrapped screen', 'WWS', 'premium screen', 'mesh screen'], 'The keystone wire wrap on ribs over the base pipe whose slot holds the gravel while letting fluid through.', 'Slot sized below the smallest gravel; premium mesh screens use woven layers for finer sand; designed and tested to ISO 17824.', 'ISO 17824.', 'Handled with protectors; erosion at high rates or with a void in the pack.', ['SC-GRAVELPACK-SCREEN'], { standards: [{ standard: 'ISO 17824', edition: 'verify', paraphrase: 'Sand screens.', source: 'S47' }], sources: ['S42', 'S47'] });
scc('SC-GRAVELPACK-BASEPIPE', 'SC-GRAVELPACK', 'gravel-pack', 'Perforated base pipe', ['base pipe', 'drilled pipe'], 'The drilled pipe under the wrap that carries the load and passes flow into the tubing.', 'Hole pattern sized for flow area; casing-grade material.', 'ISO 17824 with the screen.', 'None beyond the string.', ['SC-GRAVELPACK-BASEPIPE']);
scc('SC-GRAVELPACK-GRAVEL', 'SC-GRAVELPACK', 'gravel-pack', 'Gravel pack sand', ['gravel', 'pack sand', 'gravel pack proppant'], 'The sized sand or ceramic placed in the annulus and the perforation tunnels that filters the formation sand.', 'Sized from formation sand sieve data (about six times the median); tested like proppant for size, sphericity, and crush.', 'API RP 19C testing where held.', 'None beyond pumping.', ['SC-GRAVELPACK-GRAVEL']);
scc('SC-GRAVELPACK-SUMPPACKER', 'SC-GRAVELPACK', 'gravel-pack', 'Sump packer and seal assembly', ['sump packer', 'bottom packer', 'seal assembly (GP)'], 'The packer set below the interval before the screen is run, and the seal assembly on the screen tail that stabs into it to close the bottom of the pack.', 'Set on wireline or tubing; gives a fixed depth reference for the screen.', 'Rated for the pack pressure.', 'Set and depth-checked before the screen run.', ['SC-GRAVELPACK-SUMPPACKER', 'SC-GRAVELPACK-SEALASSEMBLY']);
scc('SC-GRAVELPACK-CONTEXT', 'SC-GRAVELPACK', 'gravel-pack', 'Casing, formation, and washpipe (context)', ['washpipe', 'gravel pack context'], 'The perforated casing and cement, the formation, and the washpipe inside the screen, shown translucent for context.', 'The washpipe returns carrier fluid during the pack and comes out with the service tool.', 'See CM records for casing and cement.', 'None.', ['SC-GRAVELPACK-CASING', 'SC-GRAVELPACK-FORMATION', 'SC-GRAVELPACK-WASHPIPE']);
sc({ id: 'SC-STANDALONESCREEN', parent: 'SC', group: 'screens', level: 'equipment', name: 'Standalone screens and slotted liners', aliases: ['standalone screen', 'SAS', 'slotted liner', 'screen only'],
  function: 'Screens or slotted liners run across the interval without gravel, relying on the formation sand bridging on the openings.',
  tabs: { overview: 'Cheaper and simpler than a gravel pack, used in openhole horizontals in well-sorted sands; public guidance warns they plug over time in most formations. Slot width is sometimes sized to the 10 percentile grain size so the coarser grains bridge.', engineering: 'Slot or mesh sized from sieve analysis; erosion and plugging are the design limits.', safety: 'Handled with protectors on the rig.', evidence: EVS, failure_modes: 'Plugging, erosion, hot spots where flow concentrates.' }, sources: ['S42', 'S47'] });
sc({ id: 'SC-CONSOLIDATION', parent: 'SC', group: 'chemical', level: 'equipment', name: 'Chemical consolidation and resin-coated gravel', aliases: ['resin consolidation', 'plastic consolidation', 'resin-coated gravel', 'chemical sand control'],
  function: 'Resin injected into the formation to bind the sand grains, or resin-coated gravel that cures in place, leaving the wellbore free of screens.',
  tabs: { overview: 'Epoxy, furan, and phenolic systems; limited today by cost and by placement over intervals longer than a few tens of feet; resin-coated gravel has shown good early results and poor longevity in public reports.', engineering: 'Placement uniformity is the design problem; permeability loss after cure.', safety: 'Chemical handling at surface.', evidence: EVS, failure_modes: 'Uneven placement, loss of permeability, sand returning as the resin degrades.' }, sources: ['S42'], hazards: [H.chem] });

// ================================================================ pad furniture drawn since Drop 7 (LG and PP)
save({ id: 'LG', system: 'LG', level: 'system', name: 'Logistics, power, and pad infrastructure', aliases: ['logistics', 'pad infrastructure', 'LG', 'pad layout'], status: 'draft', evidence_tier: 'E3', reviewers: [], drawn_in_3d: false, sources: ['S9', 'S38'], revision: rev('Drop 8 seed'), hazards: [],
  function: 'Everything on the pad that is not process equipment: the pad itself and its berm, the lease road, containment, sand and water storage and delivery, lighting, parking, and the traffic plan that moves trucks through it.',
  tabs: { overview: 'A frac pad is a bermed, graded surface of caliche or crushed stone with a lease road in, rows for the pumps and missile, a sand area (silos or boxes), water tanks or pits with lay-flat lines, the data van and chemical units, the flowback area downwind, and parking outside the red zone. The simulator repaints the terrain, vegetation, and sky by basin and places the furniture from pad photographs read for layout only.', engineering: 'Layout follows the red zone, the crane radius over the wells, truck turning circles, and prevailing wind for the flare.', safety: 'Traffic, dust, night lighting, and the red zone boundary.', evidence: 'Pad photographs (S9); EIA regions (S38).' } });
const lg = (o) => save({ status: 'draft', evidence_tier: 'E3', reviewers: [], system: 'LG', drawn_in_3d: true, sources: ['S9'], revision: rev('Drop 8 seed'), hazards: [], tabs: { evidence: 'Pad photographs read for layout only (S9).' }, ...o });
lg({ id: 'LG-CONTAINMENT', parent: 'LG', group: 'pad', level: 'equipment', name: 'Well row containment liner', aliases: ['containment', 'liner', 'berm (well row)', 'spill containment'], function: 'The lined and bermed area around the wellheads that catches spills and washdown during the completion.', scene: 'LG-CONTAINMENT', tabs: { overview: 'A geomembrane liner with a raised berm around the row of trees; hoses and iron cross it on ramps; pumped out as it collects fluid.', engineering: 'Sized to the tree footprint plus working room.', safety: 'Trip hazard at the berm; slick liner when wet.', evidence: 'Pad photographs read for layout only (S9).' } });
lg({ id: 'LG-SANDBOXES', parent: 'LG', group: 'sand', level: 'equipment', name: 'Sand boxes (containerized sand)', aliases: ['sand box', 'sand containers', 'box sand', 'containerized proppant'], function: 'Sand delivered and stored in stackable containers that gravity-feed a conveyor to the blender, the alternative to pneumatic silos.', scene: 'LG-SANDBOXES', tabs: { overview: 'Boxes arrive full on trucks, stack two high in rows, and are set on a feeder that empties them onto the blender conveyor; no pneumatic transfer, so less dust and noise.', engineering: 'Box count from the stage proppant and the truck cycle time.', safety: 'Forklift and crane traffic; silica dust controls at the feeder.', evidence: 'Pad photographs read for layout only (S9).' }, connections: [{ target: 'PP-SANDHANDLING', direction: 'downstream', type: 'mechanical' }] });
lg({ id: 'LG-LIGHTTOWER', parent: 'LG', group: 'pad', level: 'equipment', name: 'Light towers', aliases: ['light tower', 'light plant', 'pad lighting'], function: 'Trailer-mounted mast lights placed around the pad for night operations.', scene: 'LG-LIGHTTOWER', tabs: { overview: 'Diesel or solar units with a telescoping mast and four lamp heads; placed at the well row, the pumps, and the sand area.', engineering: 'Coverage per the pad layout.', safety: 'Mast lowered before moves; glare toward the crane operator avoided.', evidence: 'Pad photographs read for layout only (S9).' } });
save({ id: 'PP-FUELGAS', system: 'PP', parent: 'PP', group: 'power', level: 'equipment', name: 'Fuel gas trailers (CNG or LNG)', aliases: ['CNG trailers', 'LNG trailers', 'fuel gas supply', 'virtual pipeline'], status: 'draft', evidence_tier: 'E3', reviewers: [], drawn_in_3d: true, scene: 'PP-FUELGAS', sources: ['S37', 'S9'], revision: rev('Drop 8 seed'), hazards: [H.gas],
  function: 'Rows of high-pressure or cryogenic gas trailers parked along the pad edge that supply fuel gas to dual-fuel engines and to the generators of an electric fleet where no field gas line exists.',
  tabs: { overview: 'Trailers are swapped by truck as they empty; a decant or vaporizer skid regulates the gas to the conditioning skid. The simulator draws them for the gas-burning fleets.', engineering: 'Trailer count from the fleet gas demand and the swap cycle.', safety: 'High-pressure or cryogenic gas; exclusion zone and no ignition sources.', evidence: 'Electric fleet article (S37); pad photographs for layout only (S9).' } });

console.log('seeded drop 8');
