// Drop 5 seed: CT and FB systems, WL-PCE size variants, wellhead notes. Every new record is "draft".
// Run: node scripts/seed-drop5.mjs
import fs from 'node:fs';
import path from 'node:path';

const DATE = '2026-09-29';
const rev = (note) => ({ rev: 'A', author: 'AI draft', date: DATE, note });
const REC = (sys) => path.resolve('content/records', sys);
const load = (sys, id) => JSON.parse(fs.readFileSync(path.join(REC(sys), id + '.json'), 'utf8'));
const save = (r) => { fs.mkdirSync(REC(r.system), { recursive: true }); fs.writeFileSync(path.join(REC(r.system), r.id + '.json'), JSON.stringify(r, null, 2) + '\n'); };
const H = {
  pressure: { class: 'Stored pressure', control: 'Pressure test before opening to the well; bleed down and verify zero before breaking any connection.' },
  lof: { class: 'Line of fire', control: 'Stay clear of the coil path, the gooseneck, and flowback iron under flow.' },
  pinch: { class: 'Pinch point', control: 'Hands clear of the injector chains, the reel, and the stripper door.' },
  dropped: { class: 'Dropped object', control: 'Certified lifting gear; no one under the injector while it is suspended.' },
  h2s: { class: 'H2S', control: 'Monitors and wind indicators at the flowback spread; escape sets staged.' },
  fire: { class: 'Fire and flammable gas', control: 'Flare and tanks sited downwind; hot work controls; static bonding on tanks and lines.' },
  noise: { class: 'Noise', control: 'Hearing protection at the power pack, flare, and choke house.' },
  erosion: { class: 'Erosion', control: 'Wall thickness checks on chokes, tees, and elbows carrying proppant returns.' },
};

// ---- sources
const srcPath = path.resolve('content/sources.json');
const sources = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
const add = (s) => { if (!sources.find(x => x.id === s.id)) sources.push(s); };
add({ id: 'S23', title: 'API RP 16ST, Coiled Tubing Well Control Equipment Systems', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S24', title: 'Coiled tubing BOP and pressure control equipment guide', publisher: 'Drilling Manual (web)', edition: '2022, modified 2026', access: 'Public', tier: 'E2', url: 'https://www.drillingmanual.com/coiled-tubing-bop-pressure-control-equipment/' });
add({ id: 'S25', title: 'Flowback and well testing: ensuring safe, efficient production startups', publisher: 'FESCO, Ltd.', edition: '2025-05-28', access: 'Public', tier: 'E2', url: 'https://www.fescoinc.com/news/flowback-and-well-testing-ensuring-safe-efficient-production-startups' });
add({ id: 'S26', title: 'API RP 5C7, Coiled Tubing Operations in Oil and Gas Well Services', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
fs.writeFileSync(srcPath, JSON.stringify(sources, null, 2) + '\n');

// ---- glossary
const gPath = path.resolve('content/glossary.json');
const glossary = JSON.parse(fs.readFileSync(gPath, 'utf8'));
const gadd = (g) => { const i = glossary.findIndex(x => x.term === g.term); if (i >= 0) glossary[i] = g; else glossary.push(g); };
gadd({ term: 'Injector head', aliases: ['injector', 'CT injector', 'chain injector'], system: 'CT', record: 'CT-STACK-INJECTOR', definition: 'The chain-driven gripper machine on top of the coiled tubing stack that pushes the coil into the well against pressure and pulls it out.' });
gadd({ term: 'Stripper', aliases: ['packoff', 'stripper packer', 'side-door stripper'], system: 'CT', record: 'CT-STACK-STRIPPER', definition: 'The hydraulic elastomer seal around the moving coiled tubing that keeps well pressure in while the coil runs.' });
gadd({ term: 'Quad BOP', aliases: ['CT BOP', 'four-ram BOP', 'quad'], system: 'CT', record: 'CT-STACK-QUADBOP', definition: 'The coiled tubing blowout preventer with blind, shear, slip, and pipe rams stacked in one body.' });
gadd({ term: 'Choke manifold', aliases: ['flowback manifold', 'dual choke', 'choke skid'], system: 'FB', record: 'FB-CHOKEMANIFOLD', definition: 'The skid of plug valves and chokes that takes the well from treating pressure down to separator pressure during flowback, with two runs so one choke can be changed while the other flows.' });
gadd({ term: 'Sand separator', aliases: ['sand trap', 'desander', 'cyclonic separator'], system: 'FB', record: 'FB-SANDSEPARATOR', definition: 'The pressure vessel that drops proppant and plug debris out of the flowback stream before the chokes and separator erode.' });
fs.writeFileSync(gPath, JSON.stringify(glossary, null, 2) + '\n');

// ================================================================ WL updates: size variants
{
  const r = load('WL', 'WL-PCE');
  r.glb = '/glb/WL/WL-PCE.7-15K.glb';
  r.variants = [{ key: '5-15K', label: '5-1/8 in. 15K', glb: '/glb/WL/WL-PCE.5-15K.glb' }, { key: '7-15K', label: '7-1/16 in. 15K', glb: '/glb/WL/WL-PCE.7-15K.glb' }];
  r.tabs.overview = r.tabs.overview.replace('Bottom to top:', 'Bottom to top (the model is drawn in 5-1/8 and 7-1/16 in. bores; choose the size above the viewer):');
  r.tabs.engineering = (r.tabs.engineering || '') + ' The bottom adapter in the model is a hands-free connector that lands over the tree top adapter, so the crane sets the stack and the latch engages without a person on the tree. The wireline valve is a block body with two ram levels and tie-rod actuators on both sides.';
  r.revision = rev('Drop 5: rebuilt with block wireline valve, hands-free adapter, size variants'); save(r);
  for (const id of ['WL-PCE-WELLHEADADAPTER', 'WL-PCE-QUICKUNION', 'WL-PCE-WIRELINEVALVE', 'WL-PCE-TOOLTRAP', 'WL-PCE-PUMPINSUB', 'WL-PCE-BALLCHECK', 'WL-PCE-LUBRICATOR', 'WL-PCE-TOOLCATCHER', 'WL-PCE-GREASEHEAD', 'WL-PCE-LINEWIPER']) {
    const c = load('WL', id); c.glb = '/glb/WL/WL-PCE.7-15K.glb'; save(c);
  }
  const wa = load('WL', 'WL-PCE-WELLHEADADAPTER');
  wa.name = 'Bottom adapter (hands-free connector)';
  wa.aliases = ['tree adapter (wireline)', 'quick connect adapter', 'stack adapter', 'hands-free adapter'];
  wa.tabs.overview = 'The lowest piece of the stack: a funnel skirt guides the stack onto the tree top adapter, a latch collar locks it, and a spool above carries the first quick union. Remote-latching connectors keep people off the tree while the crane lands the stack; a studded flange crossover is the bolted alternative.';
  save(wa);
  const wh = load('WH', 'WH-TUBINGHEAD');
  wh.tabs.engineering = (wh.tabs.engineering || '') + ' The wellhead model now carries a 7-1/16 in. 15K tree adapter and block-body side outlet valves to match the standard stack.';
  save(wh);
}

// ================================================================ CT system
const EVC = 'Public coiled tubing pressure control guide (S24), API RP 16ST and API RP 5C7 scope (S23, S26), field practice (S9).';
const CT_GLB = '/glb/CT/CT-STACK.glb';
const ct = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'CT', drawn_in_3d: false, sources: ['S9', 'S23', 'S24'], revision: rev('Drop 5 seed'), hazards: [H.pressure, H.lof], ...o });
const ctc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => ct({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVC, ...(extra.tabs || {}) }, drawn_in_3d: !!(nodes || extra.scene), ...(nodes ? { glb: CT_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

ct({ id: 'CT', level: 'system', name: 'Coiled tubing intervention', aliases: ['coiled tubing', 'CT', 'coil', 'CTU', 'drillout'], scene: 'CT-UNIT', drawn_in_3d: true,
  function: 'The continuous-pipe unit that runs a mill on the end of coiled tubing through the frac plugs after the last stage, circulates the debris out, and hands the well to flowback; also used for cleanouts, fishing, and nitrogen lifts.',
  tabs: {
    overview: 'Coiled tubing is a continuous steel pipe spooled on a reel. The injector head on top of the pressure control stack grips it between two chains and pushes it into the well against wellhead pressure or pulls it out, while the stripper seals around the moving pipe and the quad BOP below provides the well control barriers. For a drillout the bottomhole assembly is a motor and mill: fluid pumped down the coil drives the motor, the mill grinds each composite plug from the heel toward the toe, and returns carry the cuttings up the annulus through the flowback line.\n\nThe unit is a truck or trailer with the reel, a power pack, and a control cabin; a crane or the unit\'s own mast holds the injector over the tree. The stack lands on the same top adapter the wireline lubricator used.',
    engineering: 'Coil sizes 2 to 2-7/8 in. are common for horizontal drillouts; the working limit is set by the coil\'s fatigue life, the injector pull, and the ability to reach the toe without lockup. Pressure control equipment is rated to the wellhead pressure; strippers see lower dynamic ratings than the BOP.',
    connections: 'Stack on the tree top adapter; returns through wing B to the flowback spread; fluid pumped from the CT pump through the reel swivel into the coil.',
    safety: 'Two barriers around the coil while the well is live: stripper in motion and pipe rams when stopped. The injector is a suspended load; the gooseneck and coil are a line-of-fire hazard; returns carry solids at pressure.',
    specs: 'Injector pull 60,000 to 100,000 lb classes; quad BOP 10,000 psi working pressure common; stripper dynamic rating lower than the BOP (S24).',
    evidence: EVC, operations: 'After the last frac stage: rig up, test, run in, mill plugs heel to toe, circulate clean, pull out, rig down, hand over to flowback.',
    failure_modes: 'Coil lockup in the lateral, motor stalls, mill wear, stripper leaks, coil fatigue cracks, lost circulation of returns.',
  }, standards: [{ standard: 'API RP 16ST', edition: 'verify', paraphrase: 'Recommended practice for coiled tubing well control equipment systems: stack-up, ratings, testing.', source: 'S23' }, { standard: 'API RP 5C7', edition: 'verify', paraphrase: 'Recommended practice for coiled tubing operations: string management, fatigue, and running practices.', source: 'S26' }],
  hazards: [H.pressure, H.lof, H.dropped, H.pinch], sources: ['S9', 'S23', 'S24', 'S26'] });

ct({ id: 'CT-STACK', parent: 'CT', group: 'pressure-control', level: 'equipment', name: 'Coiled tubing pressure control stack and injector', aliases: ['CT stack', 'CT BOP stack', 'injector stack', 'CT PCE'],
  function: 'The assembly on the tree during a drillout: hands-free bottom adapter, quad BOP, riser, side-door stripper, injector head with its chains and motors, and the gooseneck that guides the coil from the reel into the injector.',
  tabs: {
    overview: 'Bottom to top: the bottom adapter lands on the tree top adapter; the quad BOP carries pipe, slip, shear, and blind rams; the riser gives room for the BHA above the rams; the stripper seals around the moving coil; the injector head grips the coil between two chains fitted with gripper blocks, driven by hydraulic motors, and the load cell under it reads weight; the gooseneck bends the coil from the reel over into the injector on rollers. Use the section and translucent tools to follow the coil down through the stack.',
    engineering: 'Rated to the wellhead pressure at the BOP; the riser length is set by the longest BHA; the injector pull and snub ratings are matched to the coil and the expected pressure. Hydraulic supply from the power pack; all functions run from the control cabin.',
    connections: 'Tree top adapter below; kill and equalizing ports on the BOP; coil to the reel through the gooseneck; hydraulic lines to the power pack.',
    safety: 'Barrier philosophy: stripper while moving, pipe rams when stopped, shear and blind for an emergency; stack tested before the swab valve is opened.',
    evidence: EVC, operations: 'Assembled on the ground, tested, lifted onto the tree as one piece by the crane or mast.',
    failure_modes: 'Stripper element wear, ram seal leaks, chain and gripper wear, gooseneck roller damage, hydraulic leaks.',
  }, drawn_in_3d: true, glb: CT_GLB, ghost_nodes: ['CT-STACK-COIL'],
  mesh_nodes: ['CT-STACK-BOTTOMADAPTER', 'CT-STACK-QUADBOP', 'CT-STACK-RISER', 'CT-STACK-STRIPPER', 'CT-STACK-INJECTOR', 'CT-STACK-MOTOR', 'CT-STACK-CHAIN', 'CT-STACK-GOOSENECK', 'CT-STACK-COIL'],
  hazards: [H.pressure, H.lof, H.dropped, H.pinch] });
ctc('CT-STACK-BOTTOMADAPTER', 'CT-STACK', 'pressure-control', 'Bottom adapter (hands-free connector)', ['CT adapter', 'quick connect', 'stack adapter'], 'The connector at the bottom of the CT stack that lands over the tree top adapter and latches without anyone on the tree.', 'Funnel skirt, latch collar, and a flanged spool to the BOP; the same family of connector as the wireline stack uses.', 'Rated with the stack; latch profile matched to the tree adapter.', 'Latch confirmed and tested before the swab valve is opened.', ['CT-STACK-BOTTOMADAPTER']);
ctc('CT-STACK-QUADBOP', 'CT-STACK', 'pressure-control', 'Quad BOP (blind, shear, slip, pipe rams)', ['quad BOP', 'CT BOP', 'four-ram preventer', 'combi BOP'], 'The blowout preventer of the coiled tubing stack: four ram sets in one block body, hydraulically closed, that seal the well with the coil in place, hold the coil, cut it, or seal the open bore.',
  'From the top: blind rams seal the open bore with no coil in it; shear rams cut the coil and leave the cut open for circulation; slip rams grip the coil against movement; pipe rams seal around the coil (S24). Equalizing and kill ports let pressure be balanced across rams and fluid pumped below them. Tie-rod actuators on both sides of each ram level; manual locks on some designs.', 'Working pressure 10,000 psi common (S24); ram inserts sized to the coil; bore matched to the BHA.', 'Rams are function-tested before the job and pressure-tested on the stack; the shear ram is the last resort and is only closed with the coil stopped.', ['CT-STACK-QUADBOP'], { standards: [{ standard: 'API RP 16ST', edition: 'verify', paraphrase: 'Ram configuration, ratings, and testing for coiled tubing BOPs.', source: 'S23' }] });
ctc('CT-STACK-RISER', 'CT-STACK', 'pressure-control', 'Riser spool', ['riser', 'lubricator (CT)', 'BHA riser'], 'The flanged spool between the BOP and the stripper that gives the bottomhole assembly a place to sit above the rams when the coil is pulled up.',
  'Length set by the longest BHA plus a margin so the rams can close on bare coil with the tools above them.', 'Rated with the stack; flanged both ends.', 'A BHA parked in the riser is above the rams; the stripper is the only seal until the rams are closed on the coil above the BHA.', ['CT-STACK-RISER']);
ctc('CT-STACK-STRIPPER', 'CT-STACK', 'pressure-control', 'Side-door stripper (packoff)', ['stripper', 'stripper packer', 'packoff', 'side door stripper'], 'The hydraulic seal around the moving coil at the top of the stack: pistons squeeze an elastomer element onto the pipe so the well stays sealed while the coil runs.',
  'The side-door design lets the element be changed with the coil in the stack by opening a door; conventional and radial designs exist (S24). Element life depends on pressure, speed, and how clean the coil is; a second stripper is sometimes stacked as a spare.', 'Dynamic pressure ratings are below the BOP rating (S24); element size per the coil.', 'Element change on a live well needs two barriers below (pipe rams and a second seal) (S24).', ['CT-STACK-STRIPPER']);
ctc('CT-STACK-INJECTOR', 'CT-STACK', 'injector', 'Injector head frame', ['injector head', 'injector', 'chain injector'], 'The machine that pushes the coil into the well and pulls it out: a frame with two counter-rotating chains carrying gripper blocks that clamp the coil, hydraulic motors, a skate and tension system, and a load cell that reads pipe weight.',
  'Pull and snub ratings (thousands of pounds in each direction) set what coil and what wellhead pressure the unit can handle; gripper blocks are sized to the coil; the load cell drives the weight indicator in the cabin.', 'Pull classes of 60,000 to 100,000 lb are common; hydraulic drive from the power pack.', 'Suspended by the crane or mast; the chain and block area is a pinch hazard; the coil between the reel and gooseneck is a line-of-fire hazard.', ['CT-STACK-INJECTOR'], { hazards: [H.dropped, H.pinch, H.lof] });
ctc('CT-STACK-CHAIN', 'CT-STACK-INJECTOR', 'injector', 'Drive chains and gripper blocks', ['chains', 'gripper blocks', 'grippers'], 'The two chain loops with gripper blocks that clamp the coil between them and move it up or down as the chains turn.',
  'Blocks are contoured to the coil OD and changed for a different coil size; chain tension is hydraulic so the grip follows the pipe.', 'Block sets per coil size; chain tension setpoints per the coil and pressure.', 'Pinch points; blocks and chains inspected for wear each job.', ['CT-STACK-CHAIN'], { hazards: [H.pinch] });
ctc('CT-STACK-MOTOR', 'CT-STACK-INJECTOR', 'injector', 'Hydraulic drive motors', ['injector motors', 'drive motors'], 'The hydraulic motors on the injector frame that turn the drive chains, with a brake that holds the coil when the motors stop.',
  'Speed and torque set by the power pack flow and pressure; the brake holds against the snub or pull load when stopped.', 'Two or four motors per injector.', 'Brake function tested before running; hot hydraulic lines.', ['CT-STACK-MOTOR']);
ctc('CT-STACK-GOOSENECK', 'CT-STACK-INJECTOR', 'injector', 'Gooseneck (guide arch)', ['gooseneck', 'guide arch', 'arch'], 'The arched roller guide on top of the injector that bends the coil from the reel over into the vertical run of the injector.',
  'Radius chosen against the coil size to limit bending strain; rollers support the pipe around the arch; a straightener or counter-bend is fitted on some units.', 'Radius in the 72 to 120 in. class for common coil sizes; rollers per pipe size.', 'The coil over the arch is a line-of-fire hazard if it parts; no one under the arch while running.', ['CT-STACK-GOOSENECK'], { hazards: [H.lof] });
ctc('CT-STACK-COIL', 'CT-STACK', 'string', 'Coiled tubing (through the stack)', ['coil', 'CT string', 'tubing'], 'The length of coiled tubing shown running from the reel over the gooseneck, down through the injector, stripper, and BOP into the well.',
  'Continuous welded steel pipe in sizes such as 2, 2-3/8, and 2-7/8 in.; wall thickness tapered along the string on long reels; fatigue life tracked per foot in the string management software.', 'Yield strength grades in the 80,000 to 130,000 psi class; wall 0.156 to 0.204 in. typical.', 'Fatigue cracks at the gooseneck bend and at the reel are the common string failure; the string is retired on a cycle count.', ['CT-STACK-COIL'], { standards: [{ standard: 'API RP 5C7', edition: 'verify', paraphrase: 'Coiled tubing string management and running practices.', source: 'S26' }] });

ct({ id: 'CT-UNIT', parent: 'CT', group: 'unit', level: 'equipment', name: 'Coiled tubing unit (truck or trailer)', aliases: ['CT unit', 'CTU', 'coil truck', 'reel trailer'], scene: 'CT-UNIT', drawn_in_3d: true,
  function: 'The vehicle carrying the reel with the coil, the power pack, and the control cabin; the injector rides on a crane or on the unit\'s own mast.',
  tabs: { overview: 'Land units are trucks or trailers; the reel is the heaviest item and its capacity fixes the longest well the unit can reach. The operator in the cabin sees weight, depth, pressures, and rates and runs the injector, reel, and BOP functions.', engineering: 'Reel capacity in feet of a given coil size; power pack horsepower drives the injector and reel; a mast unit removes the need for a crane on some pads.', connections: 'Coil from the reel to the gooseneck; hydraulic lines to the injector and stack; fluid from the CT pump through the reel swivel.', safety: 'Reel rotation and the coil path are line-of-fire and pinch hazards; the unit is positioned so the operator sees the injector.', evidence: EVC, operations: 'Spotted, rigged, and tested before the drillout; cycles with the flowback crew after.', failure_modes: 'Reel drive faults, swivel leaks, hydraulic leaks, cabin instrument faults.' }, hazards: [H.lof, H.pinch] });
ctc('CT-REEL', 'CT-UNIT', 'unit', 'Reel and levelwind', ['reel', 'drum', 'levelwind', 'spooler'], 'The powered drum that stores the coil and keeps back-tension on it as the injector runs, with a levelwind that lays the pipe evenly.', 'The reel does not push or pull the pipe into the well; the injector does. The reel holds tension so the pipe stays wrapped and feeds the gooseneck; the swivel on the reel axle admits pumped fluid to the coil.', 'Capacity per coil size; back-tension setpoints.', 'Rotating reel; pinch points at the levelwind.', null, { scene: 'CT-REEL', hazards: [H.pinch, H.lof] });
ctc('CT-POWERPACK', 'CT-UNIT', 'unit', 'Power pack', ['power pack', 'hydraulic power unit', 'HPU (CT)'], 'The diesel-driven hydraulic power unit that supplies the injector, reel, stripper, and BOP functions.', 'Sized to the injector motors; accumulators on the BOP circuit so rams close with the engine stopped.', 'Hydraulic pressure and flow per the injector.', 'Hot exhaust and hydraulic lines; noise.', null, { scene: 'CT-POWERPACK', hazards: [H.noise] });
ctc('CT-CONTROLCABIN', 'CT-UNIT', 'unit', 'Control cabin', ['cabin', 'control cab', 'operator cab'], 'The operator station with the weight indicator, depth counter, circulating and wellhead pressure gauges, and the controls for injector, reel, stripper, and BOP.', 'Depth is counted at the injector and corrected for stretch; weight comes from the injector load cell; the BOP panel has its own accumulator.', 'Instruments per API RP 16ST practice.', 'The cabin is outside the stack drop zone; emergency BOP functions are on a dedicated panel.', null, { scene: 'CT-CONTROLCABIN' });
ct({ id: 'CT-BHA', parent: 'CT', group: 'bha', level: 'equipment', name: 'Drillout bottomhole assembly (motor and mill)', aliases: ['BHA', 'drillout BHA', 'mill assembly', 'motor and mill'], scene: 'CT-DOWNHOLE', drawn_in_3d: true,
  function: 'The tools on the end of the coil for a plug drillout: coil connector, dual check valves, disconnect, circulation sub, positive-displacement motor, and the mill that grinds the composite plugs.',
  tabs: { overview: 'Fluid pumped down the coil drives the motor, which turns the mill; weight is applied through the injector. Each plug takes minutes when the mill is sharp and returns are good; cuttings are carried to surface in the annulus. Dual check valves keep well pressure out of the coil; the disconnect lets the coil be freed if the BHA sticks.', engineering: 'Motor sized to the coil flow; mill type chosen for composite plugs and the casing; agitators or extended-reach tools help the coil reach the toe.', connections: 'Coil connector to the coil; mill on the motor.', safety: 'Check valves are the barrier inside the coil; the disconnect is the last resort before cutting the coil.', evidence: EVC, operations: 'Made up on the ground, tested, run through the stack.', failure_modes: 'Motor stall, mill wear, stuck BHA, check valve failure.' }, hazards: [H.pressure] });
ctc('CT-MILL', 'CT-BHA', 'bha', 'Mill', ['mill', 'plug mill', 'junk mill'], 'The cutting tool on the motor that grinds each composite frac plug into pieces small enough to circulate out.', 'Dressed with carbide or hardfacing; diameter slightly under the casing drift; profile chosen for composite plugs.', 'Diameter per the casing; hours per mill tracked.', 'Worn mills slow the drillout and leave larger debris.', null, { scene: 'CT-MILL' });
ctc('CT-MOTOR', 'CT-BHA', 'bha', 'Positive-displacement motor', ['PDM', 'mud motor', 'downhole motor'], 'The downhole motor that converts pumped fluid into rotation of the mill.', 'Rotor and stator in a helical pair; speed proportional to flow; torque proportional to pressure drop across the motor.', 'Sized to the coil flow rate.', 'Stalls when weight is too high; pressure spike is the indicator.', null);

// ================================================================ FB system
const EVF = 'Public flowback and well testing overview (S25), field practice (S9).';
const FB_GLB = '/glb/FB/FB-CHOKEMANIFOLD.glb';
const fb = (o) => save({ status: 'draft', evidence_tier: 'E3', reviewers: [], system: 'FB', drawn_in_3d: false, sources: ['S9', 'S25'], revision: rev('Drop 5 seed'), hazards: [H.pressure, H.erosion], ...o });
const fbc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => fb({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVF, ...(extra.tabs || {}) }, drawn_in_3d: !!(nodes || extra.scene), ...(nodes ? { glb: FB_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

fb({ id: 'FB', level: 'system', name: 'Flowback and well testing', aliases: ['flowback', 'well test', 'flowback spread', 'initial flowback'], scene: 'FB-SPREAD', drawn_in_3d: true,
  function: 'The temporary surface equipment that takes the well from the frac and drillout to production: it controls the well on a choke, removes sand and plug debris, separates gas, oil, and water for measurement, and sends gas to a flare and liquids to tanks or the facility.',
  tabs: {
    overview: 'After the drillout the well is opened through wing B to the flowback spread. Returns are unpredictable at first: frac water, then oil and gas, with proppant and plug debris. A sand separator or plug catcher takes the solids first, the choke manifold holds back pressure and controls the rate, and a test separator splits the phases so each can be measured. Gas goes to the flare stack until the sales line is ready; liquids go to tanks or the production facility.\n\nThe flowback period measures the well\'s early performance, recovers frac fluid, and protects the production equipment from the solids and pressure swings of the first days.',
    engineering: 'Equipment is rated for the shut-in wellhead pressure; the choke manifold usually 10,000 psi with the downstream vessels at lower ratings behind the chokes; sour service where H2S is possible. Erosion by proppant sets wall thickness checks on chokes, tees, and elbows.',
    connections: 'From wing B of the tree through flowback iron to the sand separator, choke manifold, separator, then flare and tanks.',
    safety: 'Live iron at wellhead pressure upstream of the chokes; flammable gas at the separator, tanks, and flare; H2S possible; erosion failures on the sand-laden side.',
    specs: 'Choke manifold 10,000 psi common; separators 1,440 psi class typical; flare sited per the site plan.',
    evidence: EVF, operations: 'Rigged up during the drillout; runs continuously for days to weeks; handed to production when the well is clean and the facility can take it.',
    failure_modes: 'Choke washout, sand carryover, separator upsets on slugs, flare outages, frozen lines in winter.',
  }, hazards: [H.pressure, H.erosion, H.fire, H.h2s], sources: ['S9', 'S25'] });

fb({ id: 'FB-CHOKEMANIFOLD', parent: 'FB', group: 'pressure-control', level: 'equipment', name: 'Dual choke manifold', aliases: ['choke manifold', 'choke skid', 'dual choke', 'flowback manifold'], scene: 'FB-CHOKEMANIFOLD',
  function: 'The skid of plug valves and chokes that drops the well pressure to separator pressure and sets the flow rate, with two parallel choke runs so one choke can be changed while the well flows through the other, and a bypass.',
  tabs: {
    overview: 'Flow enters an inlet header with an isolation plug valve and splits to two runs. Each run has an upstream plug valve, a choke, and a downstream plug valve; one choke is adjustable (a stem and handwheel with a position indicator) and the other positive (a fixed bean in a housing). A bypass run with plug valves lets the manifold be isolated. The outlet header carries a pressure gauge and goes to the separator. Chokes are changed on the idle run while the other flows.',
    engineering: 'Rated to the shut-in wellhead pressure, 10,000 psi common; 3 in. 1502 hammer-union iron; sour-service trim where needed. Choke size in 64ths of an inch sets the rate; the operator opens up in steps as the well cleans up.',
    connections: 'Inlet from the sand separator (or straight from the wellhead iron); outlet to the test separator; gauge and sample ports.',
    safety: 'Full wellhead pressure on the inlet side; choke bodies erode with sand and are checked; no one works on a run that is not isolated and bled.',
    specs: 'Choke sizes 8/64 to 128/64 in.; 3 in. 10K iron; two runs plus bypass.',
    evidence: EVF, operations: 'Choke size stepped up over hours to days; changes logged with the rates.',
    failure_modes: 'Choke washout, plug valve seal leaks, sand packing in the runs, gauge failures.',
  }, drawn_in_3d: true, glb: FB_GLB, mesh_nodes: ['FB-CHOKEMANIFOLD-SKID', 'FB-CHOKEMANIFOLD-INLET', 'FB-CHOKEMANIFOLD-PLUGVALVE', 'FB-CHOKEMANIFOLD-ADJUSTABLECHOKE', 'FB-CHOKEMANIFOLD-POSITIVECHOKE', 'FB-CHOKEMANIFOLD-BYPASS', 'FB-CHOKEMANIFOLD-OUTLET', 'FB-CHOKEMANIFOLD-GAUGE'],
  hazards: [H.pressure, H.erosion] });
fbc('FB-CHOKEMANIFOLD-SKID', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Skid and supports', ['skid', 'choke skid frame'], 'The steel frame the manifold is built on, with pipe supports and a drip pan.', 'Lifted as one piece; anchored against reaction loads.', 'Sized for the iron and the lift.', 'Trip hazards; lifting.', ['FB-CHOKEMANIFOLD-SKID']);
fbc('FB-CHOKEMANIFOLD-INLET', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Inlet header and run piping', ['inlet header', 'run piping', 'manifold iron'], 'The 3 in. hammer-union iron that brings flow from the well to the runs and connects the valves and chokes.', 'Integral fittings and tees rated with the manifold; unions at the ends for the flowback iron.', '3 in. 1502 class, 10,000 psi.', 'Erosion at tees and elbows; wall checks.', ['FB-CHOKEMANIFOLD-INLET'], { hazards: [H.pressure, H.erosion] });
fbc('FB-CHOKEMANIFOLD-PLUGVALVE', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Plug valves', ['plug valve', 'lo-torq valve', 'isolation valve'], 'The quarter-turn plug valves that isolate each run and the bypass so a choke can be changed or a run bled with the well flowing through the other.', 'A tapered or cylindrical plug turns a quarter turn in a lubricated body; the position bar on the stem shows open or closed. Greased on a schedule so they turn under pressure.', 'Rated with the manifold; 3 in. class.', 'Never opened with pressure trapped on the other side without equalizing; the position bar is the field check.', ['FB-CHOKEMANIFOLD-PLUGVALVE']);
fbc('FB-CHOKEMANIFOLD-ADJUSTABLECHOKE', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Adjustable choke', ['adjustable choke', 'needle choke', 'handwheel choke'], 'The choke whose opening is set by a stem and handwheel, with an indicator reading in 64ths of an inch, used to bring the well on and change rate in steps.', 'A needle and seat; the stem screws in and out; erosion-resistant trim. Used for the fine control early in flowback, then swapped for a positive bean once the rate settles.', 'Sizes to 2 in. bore; 10,000 psi.', 'Erosion of the needle and seat with sand; the indicator drifts as the trim wears.', ['FB-CHOKEMANIFOLD-ADJUSTABLECHOKE']);
fbc('FB-CHOKEMANIFOLD-POSITIVECHOKE', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Positive choke', ['positive choke', 'bean choke', 'fixed choke'], 'The choke with a fixed-bore bean held in a housing under a hammer-union cap, giving a repeatable rate once the well has settled.', 'Beans are changed by isolating the run, bleeding, and swapping the bean; the bore is stamped in 64ths.', 'Bean sizes per the program; 10,000 psi housing.', 'The run must be isolated and bled before the cap comes off.', ['FB-CHOKEMANIFOLD-POSITIVECHOKE']);
fbc('FB-CHOKEMANIFOLD-BYPASS', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Bypass run', ['bypass', 'bypass line'], 'The run around both chokes, normally closed, used to equalize or to flow unchoked when the well is dead.', 'Plug valves at both ends.', 'Same iron as the runs.', 'Opened only when both chokes are isolated or the well is dead.', ['FB-CHOKEMANIFOLD-BYPASS']);
fbc('FB-CHOKEMANIFOLD-OUTLET', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Outlet header', ['outlet header', 'downstream header'], 'The header collecting the runs downstream of the chokes and leading to the separator.', 'Downstream pressure is separator pressure plus line loss; still rated with the manifold because a stuck choke can pass full pressure.', '3 in. class.', 'Downstream iron is not low pressure until the separator relief is proven.', ['FB-CHOKEMANIFOLD-OUTLET']);
fbc('FB-CHOKEMANIFOLD-GAUGE', 'FB-CHOKEMANIFOLD', 'pressure-control', 'Pressure gauges', ['gauge', 'pressure gauge', 'transducer'], 'The gauges and transducers reading upstream and downstream choke pressure, which with the choke size give the operator the well\'s deliverability trend.', 'Gauge with a needle valve; transducers feed the flowback data system.', 'Ranges to the manifold rating.', 'Needle valve closed before a gauge is changed.', ['FB-CHOKEMANIFOLD-GAUGE']);

fb({ id: 'FB-SANDSEPARATOR', parent: 'FB', group: 'solids', level: 'equipment', name: 'Sand separator', aliases: ['sand separator', 'sand trap', 'desander', 'cyclonic desander'], scene: 'FB-SANDSEPARATOR', drawn_in_3d: true,
  function: 'The high-pressure vessel upstream of the chokes that drops proppant and debris out of the flowback stream by gravity or cyclone action, protecting the chokes and separator from erosion.',
  tabs: { overview: 'Flow enters tangentially or over a baffle; solids fall to the bottom and are dumped through a valve to a sand box on a schedule; clean flow leaves the top. Two units are often run in parallel so one can be dumped while the other flows.', engineering: 'Rated to wellhead pressure (10,000 psi common); capacity in pounds of sand between dumps; erosion-resistant inlet.', connections: 'Wellhead iron in; choke manifold out; dump line to the sand box.', safety: 'Dumping a live vessel is a controlled operation; erosion at the inlet.', evidence: EVF, operations: 'Dump frequency tracked against sand returns; sand volumes recorded.', failure_modes: 'Sand carryover, inlet erosion, dump valve washout.' }, hazards: [H.pressure, H.erosion] });
fb({ id: 'FB-PLUGCATCHER', parent: 'FB', group: 'solids', level: 'equipment', name: 'Plug catcher', aliases: ['plug catcher', 'debris catcher', 'junk catcher'], scene: 'FB-PLUGCATCHER', drawn_in_3d: true,
  function: 'The strainer vessel that catches large pieces of milled plug, balls, and debris after the drillout so they do not reach the chokes.',
  tabs: { overview: 'A basket or strainer inside a pressure body; flow passes through and large solids stay behind; emptied by isolating and opening the body. Usually first in line during the drillout returns.', engineering: 'Rated to wellhead pressure; basket mesh sized for plug debris.', connections: 'Between the wellhead iron and the sand separator.', safety: 'Isolated and bled before opening; debris can be sharp and hot.', evidence: EVF, operations: 'Emptied per plug or on a differential pressure rise.', failure_modes: 'Basket plugging, body erosion, seal leaks.' }, hazards: [H.pressure, H.erosion] });
fb({ id: 'FB-SEPARATOR', parent: 'FB', group: 'separation', level: 'equipment', name: 'Test separator', aliases: ['test separator', 'three-phase separator', 'flowback separator', 'well test separator'], scene: 'FB-SEPARATOR', drawn_in_3d: true,
  function: 'The vessel downstream of the chokes that separates gas, oil, and water so each can be metered, giving the first measured production of the well.',
  tabs: { overview: 'A horizontal three-phase vessel with an inlet diverter, a weir between oil and water, level controls, and a gas outlet with a back-pressure valve; each outlet has a meter. Retention time sets the separation quality; slugs from the well upset levels.', engineering: 'Working pressure classes such as 1,440 psi; relief valve sized for a blocked gas outlet; meters per phase.', connections: 'Choke manifold in; gas to the flare or sales; oil and water to tanks.', safety: 'Flammable inventory; relief and flare path proven before flow; H2S possible.', evidence: EVF, operations: 'Rates logged every shift or continuously; sample points for water cut and shrinkage.', failure_modes: 'Level control failures, carryover on slugs, foaming, meter fouling.' }, hazards: [H.pressure, H.fire, H.h2s] });
fb({ id: 'FB-FLARESTACK', parent: 'FB', group: 'disposal', level: 'equipment', name: 'Flare stack', aliases: ['flare', 'flare stack', 'flare boom'], scene: 'FB-FLARESTACK', drawn_in_3d: true,
  function: 'The stack with an igniter that burns gas from the separator during flowback until the sales line takes it.',
  tabs: { overview: 'Gas from the separator is piped to a vertical stack sited downwind with a pilot or electronic igniter; a knockout pot removes liquids first. Height and distance follow the site plan and radiant heat calculations.', engineering: 'Knockout, igniter, and flame detection; sized for the maximum gas rate.', connections: 'Separator gas outlet; knockout drain to a tank.', safety: 'Radiant heat and flammable gas; siting and wind; ignition confirmed before flow.', evidence: EVF, operations: 'Lit before the well is opened; monitored continuously.', failure_modes: 'Flameout, liquid carryover, igniter failures.' }, hazards: [H.fire] });
fb({ id: 'FB-TANKS', parent: 'FB', group: 'disposal', level: 'equipment', name: 'Flowback tanks', aliases: ['flowback tanks', 'frac tanks (flowback)', 'gauge tanks', 'holding tanks'], scene: 'FB-TANKS', drawn_in_3d: true,
  function: 'The tanks that receive oil and water from the separator for gauging and haul-off or transfer to the facility.',
  tabs: { overview: 'Gauged by hand or level sensor to measure liquid volumes; oil and water in separate tanks; vapor handled by a vent or a vapor recovery unit.', engineering: 'Atmospheric or low-pressure tanks; bonding and grounding; secondary containment.', connections: 'Separator liquid outlets; truck load-out; vent or VRU.', safety: 'Flammable vapor at hatches; confined space; grounding.', evidence: EVF, operations: 'Gauged per shift; haul-off scheduled.', failure_modes: 'Overfills, vent freezing, corrosion.' }, hazards: [H.fire] });
fb({ id: 'FB-FLOWIRON', parent: 'FB', group: 'pressure-control', level: 'equipment', name: 'Flowback iron', aliases: ['flowback line', 'flow line', 'well test iron', 'high-pressure flowback piping'],
  function: 'The high-pressure hammer-union or flanged piping from wing B of the tree to the solids equipment and choke manifold, rated for the shut-in wellhead pressure.',
  tabs: { overview: 'Same family as the treating iron but sized for flow rather than pumping; runs are restrained and kept short; elbows and tees are the erosion points.', engineering: '3 in. 10K class common; restraints; wall thickness inspection.', connections: 'Wing B to the plug catcher, sand separator, and choke manifold.', safety: 'Live at wellhead pressure; erosion; restraints.', evidence: EVF, operations: 'Laid at rig-up; inspected each shift.', failure_modes: 'Erosion washouts at turns, union leaks.' }, hazards: [H.pressure, H.erosion, H.lof] });

console.log('Drop 5 seed done');
