// Drop 9 seed: RG (workover rigs and well control: rig, BOP stack cut-away, tubing handling, snubbing), DA (data
// acquisition: frac van, transducers, flowmeters, densometers, downhole gauges, fiber, microseismic), MT
// (materials: proppants, fluid systems, additives, cement and casing grades). Every new record is "draft".
// Run: node scripts/seed-drop9.mjs
import fs from 'node:fs';
import path from 'node:path';

const DATE = '2026-09-30';
const rev = (note) => ({ rev: 'A', author: 'AI draft', date: DATE, note });
const REC = (sys) => path.resolve('content/records', sys);
const save = (r) => { fs.mkdirSync(REC(r.system), { recursive: true }); fs.writeFileSync(path.join(REC(r.system), r.id + '.json'), JSON.stringify(r, null, 2) + '\n'); };
const H = {
  pressure: { class: 'Stored pressure', control: 'Test the stack to the program pressures; bleed and verify zero before breaking any connection.' },
  wellcontrol: { class: 'Well control', control: 'BOP drills before the job; kill weight fluid or a tested barrier before the tree comes off.' },
  dropped: { class: 'Dropped object', control: 'Tubing handled with elevators and slips by trained crews; the derrick inspected before the job.' },
  pinch: { class: 'Pinch point and rotating equipment', control: 'Hands clear of slips, tongs, and the drawworks; guards on rotating parts.' },
  h2s: { class: 'H2S', control: 'Monitors at the floor and the bell nipple; escape sets staged.' },
  electrical: { class: 'Electrical', control: 'Instrument power isolated before sensor changes; cables routed off the ground.' },
  chem: { class: 'Chemicals', control: 'Data sheets on site; eye and skin protection at the additive unit; spill kits.' },
  dust: { class: 'Silica dust', control: 'Enclosed transfer, dust collection, respirators in the sand area.' },
};

// ---- sources
const srcPath = path.resolve('content/sources.json');
const sources = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
const add = (s) => { if (!sources.find(x => x.id === s.id)) sources.push(s); };
add({ id: 'S48', title: 'API Spec 16A, Drill-through Equipment (ram and annular preventers, spools)', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S49', title: 'API Std 53, Well Control Equipment Systems for Drilling Wells (stack arrangements, accumulator sizing, testing)', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S50', title: 'PetroWiki: Fracturing fluids and additives (fluid types; polymers, crosslinkers, friction reducers, biocides, buffers, surfactants, breakers, scale inhibitors)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Fracturing_fluids_and_additives' });
add({ id: 'S51', title: 'PetroWiki: Propping agents and fracture conductivity (sand, resin-coated sand, ceramic, bauxite; conductivity factors)', publisher: 'Society of Petroleum Engineers', edition: 'read 2026', access: 'Public', tier: 'E2', url: 'https://petrowiki.spe.org/Propping_agents_and_fracture_conductivity' });
add({ id: 'S52', title: 'API RP 19C, Measurement of Properties of Proppants (sieve, sphericity, crush, acid solubility)', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S53', title: 'API RP 16ST, Coiled Tubing Well Control Equipment Systems', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
fs.writeFileSync(srcPath, JSON.stringify(sources, null, 2) + '\n');

// ---- glossary
const gPath = path.resolve('content/glossary.json');
const glossary = JSON.parse(fs.readFileSync(gPath, 'utf8'));
const gadd = (g) => { const i = glossary.findIndex(x => x.term === g.term); if (i >= 0) glossary[i] = g; else glossary.push(g); };
gadd({ term: 'BOP stack', aliases: ['blowout preventer', 'BOP', 'annular', 'rams', 'nipple up', 'nipple down'], system: 'RG', record: 'RG-BOPSTACK', definition: 'The preventers bolted on the wellhead while a rig has pipe in the hole: an annular that closes on anything, pipe rams that close on the pipe, blind rams that close on an open hole, and a spool with kill and choke outlets.' });
gadd({ term: 'Nipple up and nipple down', aliases: ['NU', 'ND', 'rig up the stack'], system: 'RG', record: 'RG-BOPSTACK', definition: 'Installing (nipple up) or removing (nipple down) the BOP stack or the tree on the wellhead, with the pressure test that follows.' });
gadd({ term: 'Frac van', aliases: ['data van', 'treater van', 'control van'], system: 'DA', record: 'DA-FRACVAN', definition: 'The control room trailer where the treater runs the job from live pressure, rate, and density readings and the pump controls.' });
gadd({ term: 'Proppant', aliases: ['frac sand', 'sand', 'ceramic proppant', 'resin-coated sand', '100 mesh', '40/70'], system: 'MT', record: 'MT-PROPPANT', definition: 'The sized sand or ceramic pumped into the fracture to hold it open after the pressure comes off; sized by mesh, chosen by closure stress.' });
fs.writeFileSync(gPath, JSON.stringify(glossary, null, 2) + '\n');

// ================================================================ RG
const EVR = 'API Spec 16A (S48), API Std 53 (S49), API RP 16ST (S53), field practice (S9). Generic geometry; not an OEM design.';
const BOP_GLB = '/glb/RG/RG-BOPSTACK.glb';
const rg = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'RG', drawn_in_3d: false, sources: ['S48', 'S49', 'S9'], revision: rev('Drop 9 seed'), hazards: [H.pressure, H.wellcontrol], ...o });
const rgc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => rg({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVR, ...(extra.tabs || {}) }, drawn_in_3d: !!nodes, ...(nodes ? { glb: BOP_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

rg({ id: 'RG', level: 'system', name: 'Completion and workover rigs and well control', aliases: ['well control', 'RG', 'rigs', 'well servicing'],
  function: 'The rigs that run and pull tubing and rods and the well control equipment that keeps the well contained while they do: workover and completion rigs, snubbing units, BOP stacks, accumulators, and the tubing handling tools.',
  tabs: {
    overview: 'A frac pad sees a rig twice: a drilling rig before the completion, and a workover (completion) rig after the frac and drillout to pull the frac stack, run the production tubing with its packer and lift hardware, and set the production tree. With pipe in the hole the wellhead carries a BOP stack instead of a tree: an annular, rams, and a spool with kill and choke lines, closed hydraulically from an accumulator unit. Snubbing units run pipe into a live well against pressure. The simulator shows the rig, the BOP stack, and the tubing run in the production hookup phase.',
    engineering: 'Stack arrangements, test pressures, and accumulator sizing follow API Std 53; the preventers themselves API Spec 16A; coiled tubing stacks API RP 16ST. Rig size follows the hook load of the tubing string.',
    connections: 'Wellhead and tubing head (WH, UC); tubing and packer (UC); lift hardware (AL); flowline and choke (FB).',
    safety: 'Well control is the governing hazard: barriers verified before the tree comes off; BOP drills; pipe handling and dropped objects on the floor; H2S at the bell nipple.',
    evidence: EVR, operations: 'Move in, rig up, kill or confirm barriers, nipple down the tree, nipple up and test the stack, pull or run pipe, nipple down the stack, set and test the tree, rig down.',
    failure_modes: 'Preventer element wear, ram seal leaks, accumulator precharge loss, elevator and slip damage to tubing, drawworks brake failures.',
  }, standards: [{ standard: 'API Spec 16A', edition: 'verify', paraphrase: 'Drill-through equipment: ram and annular preventers and spools.', source: 'S48' }, { standard: 'API Std 53', edition: 'verify', paraphrase: 'Well control equipment systems: arrangements, testing, accumulators.', source: 'S49' }],
  hazards: [H.wellcontrol, H.pressure, H.dropped, H.pinch, H.h2s], sources: ['S48', 'S49', 'S53', 'S9'] });
rg({ id: 'RG-WORKOVERRIG', parent: 'RG', group: 'rig', level: 'equipment', name: 'Workover (completion) rig', aliases: ['workover rig', 'completion rig', 'pulling unit', 'service rig', 'well service rig'],
  function: 'The truck- or trailer-mounted rig with a telescoping mast that runs and pulls tubing and rods on a completed well, sized for tubing hook loads rather than drilling loads.',
  tabs: {
    overview: 'Mast raised over the well on a substructure, drawworks and blocks on wire rope, a doghouse for the crew, a power tong and slips at the floor, pipe racks alongside. In the simulator the rig appears in the production hookup phase, runs the tubing joint by joint with the block traveling, then leaves once the tree is on.',
    engineering: 'Rated by hook load and mast height (double or triple stands); drawworks and brake matched to the string weight.',
    connections: 'BOP stack on the wellhead; pipe racks; power tongs; accumulator unit.',
    safety: 'Mast raising and guying; pipe handling; the block path; well control with the stack.',
    evidence: EVR, operations: 'Rig up, pull the frac stack, nipple up the BOP, run tubing, nipple down, set the tree, rig down.',
    failure_modes: 'Brake and wire rope wear, mast pin and guy line failures, dropped tubing.',
  }, drawn_in_3d: true, scene: 'RG-WORKOVERRIG', hazards: [H.dropped, H.pinch, H.wellcontrol], sources: ['S49', 'S9'] });
rg({ id: 'RG-WORKOVERRIG-MAST', parent: 'RG-WORKOVERRIG', group: 'rig', level: 'component', name: 'Mast, crown, and traveling block', aliases: ['mast', 'derrick (workover)', 'crown block', 'traveling block', 'blocks'], function: 'The telescoping mast with the crown block at the top and the traveling block on the drilling line that lifts the tubing.', tabs: { overview: 'The block travels one joint per cycle while tubing is run; elevators under the block latch each joint.', engineering: 'Rated hook load; line count and drilling line size.', safety: 'Block path and dropped objects.', evidence: EVR }, drawn_in_3d: true, scene: 'RG-WORKOVERRIG-CROWN', sources: ['S9'], hazards: [H.dropped] });
rg({ id: 'RG-WORKOVERRIG-DRAWWORKS', parent: 'RG-WORKOVERRIG', group: 'rig', level: 'component', name: 'Drawworks and brake', aliases: ['drawworks', 'hoist', 'brake (rig)'], function: 'The winch that spools the drilling line to raise and lower the block, with the brake that holds the string.', tabs: { overview: 'Engine or electric drive; band or disc brake; the driller controls it from the doghouse or floor console.', engineering: 'Line pull and brake capacity for the string weight.', safety: 'Brake tests before running pipe.', evidence: EVR }, drawn_in_3d: true, scene: 'RG-WORKOVERRIG-DRAWWORKS', sources: ['S9'], hazards: [H.pinch] });
rg({ id: 'RG-TUBINGHANDLING', parent: 'RG', group: 'rig', level: 'equipment', name: 'Tubing handling: elevators, slips, tongs, pipe racks', aliases: ['elevators', 'slips', 'power tongs', 'pipe rack', 'tubing tongs'], function: 'The tools that hold and make up tubing at the floor: elevators under the block, slips in the rotary or bowl, power tongs for make-up torque, and the racks that stage the joints.', tabs: { overview: 'One joint per cycle: pick up from the rack, stab, make up with the tongs to the connection torque, pull the slips, lower, set the slips, latch the next joint.', engineering: 'Tong torque per the connection; slips sized to the tubing OD; elevators rated above the string weight.', safety: 'Hands clear of slips and tongs; thread protectors; tong line of fire.', evidence: EVR }, drawn_in_3d: true, scene: 'RG-WORKOVERRIG-PIPERACK', sources: ['S9'], hazards: [H.pinch, H.dropped] });
rg({ id: 'RG-SNUBBINGUNIT', parent: 'RG', group: 'rig', level: 'equipment', name: 'Snubbing unit', aliases: ['snubbing', 'hydraulic workover unit', 'HWO', 'snubbing jack'], function: 'A hydraulic unit with traveling and stationary slips that pushes or pulls pipe through a stripping stack into a well under pressure, so the well need not be killed.', tabs: { overview: 'Used to run or pull tubing on live wells and for fishing under pressure; stationary and traveling slips alternate grip as the jack strokes; a stripper and BOP stack seal on the pipe.', engineering: 'Push and pull capacity; stripper rating; stack per API Std 53.', safety: 'Pipe-light conditions push the pipe out of the hole; slip sequencing is the control.', evidence: EVR }, hazards: [H.wellcontrol, H.pressure], sources: ['S49', 'S9'] });
rg({ id: 'RG-BOPSTACK', parent: 'RG', group: 'well-control', level: 'equipment', name: 'Workover BOP stack (cut-away)', aliases: ['BOP stack', 'blowout preventer stack', 'BOPs', 'workover stack', 'annular and rams'],
  function: 'The stack of preventers on the tubing head while the rig has pipe in the hole: adapter, drilling spool with kill and choke outlets, double ram preventer (pipe rams and blind rams), annular preventer, and bell nipple.',
  tabs: {
    overview: 'Bottom to top: the adapter flange on the tubing head, a drilling spool whose two side outlets take the kill line and the choke line, a double ram body with pipe rams below (closed on the tubing profile in the cut-away) and blind rams above (open), the annular preventer whose piston squeezes a rubber element inward to seal on any pipe or the open hole, and a bell nipple with the flowline nipple that returns fluid to the tanks. Each ram has a bonnet and a hydraulic operator each side; the annular closes from below its piston. All of it is closed from the accumulator unit at the remote panel or the driller\'s panel.',
    engineering: 'Preventers per API Spec 16A; stack arrangement, test pressures, and closing times per API Std 53; the 7-1/16 in. 5K class shown suits most land completions.',
    connections: 'Tubing head below (WH); kill line and choke line on the spool (FB choke manifold on workovers); accumulator hydraulic lines; bell nipple flowline to the tanks.',
    safety: 'Pressure tested after nipple up; function tested each shift; the annular is closed first on a kick with pipe across it, rams second.',
    evidence: EVR, operations: 'Nipple up on the tubing head after the tree comes off, test, run or pull pipe, nipple down before the tree goes back on.',
    failure_modes: 'Element wear, ram packer damage, bonnet seal leaks, operator seal leaks, hydraulic hose damage.',
  }, drawn_in_3d: true, glb: BOP_GLB, scene: 'RG-BOPSTACK',
  mesh_nodes: ['RG-BOPSTACK-ADAPTER', 'RG-BOPSTACK-SPOOL', 'RG-BOPSTACK-SIDEOUTLET', 'RG-BOPSTACK-RAMBODY', 'RG-BOPSTACK-PIPERAM', 'RG-BOPSTACK-BLINDRAM', 'RG-BOPSTACK-BONNET', 'RG-BOPSTACK-OPERATOR', 'RG-BOPSTACK-ANNULARBODY', 'RG-BOPSTACK-PISTON', 'RG-BOPSTACK-ELEMENT', 'RG-BOPSTACK-BELLNIPPLE', 'RG-BOPSTACK-STUDS'],
  ghost_nodes: ['RG-BOPSTACK-TUBINGHEAD'],
  standards: [{ standard: 'API Spec 16A', edition: 'verify', paraphrase: 'Ram and annular preventer design, materials, and testing.', source: 'S48' }, { standard: 'API Std 53', edition: 'verify', paraphrase: 'Stack arrangement, testing frequency, and accumulator capacity.', source: 'S49' }], sources: ['S48', 'S49', 'S9'] });
rgc('RG-BOPSTACK-ANNULAR', 'RG-BOPSTACK', 'well-control', 'Annular preventer', ['annular', 'annular BOP', 'bag preventer', 'spherical preventer'], 'The preventer that closes a rubber element inward on any pipe size, or the open hole, by pushing a piston up under it.', 'Closed first on a kick because it seals on anything across it, including tool joints; can strip pipe through it with reduced closing pressure.', 'API Spec 16A; element rated for the well fluids and temperature.', 'Element wear checked on the function test; closing pressure regulated.', ['RG-BOPSTACK-ANNULARBODY', 'RG-BOPSTACK-PISTON', 'RG-BOPSTACK-ELEMENT']);
rgc('RG-BOPSTACK-RAMS', 'RG-BOPSTACK', 'well-control', 'Double ram preventer (pipe and blind rams)', ['ram preventer', 'pipe rams', 'blind rams', 'shear rams', 'ram BOP'], 'The body with two ram cavities: pipe rams cut to the tubing profile seal around the pipe; blind rams seal an open hole; shear rams (not shown) cut the pipe.', 'Each ram pair is driven by hydraulic operators through the bonnets; locked closed by hand or hydraulically; the cut-away shows the pipe rams closed on tubing and the blind rams open.', 'API Spec 16A; ram size matched to the pipe run.', 'Blind rams never closed with pipe across them; ram packers inspected at each test.', ['RG-BOPSTACK-RAMBODY', 'RG-BOPSTACK-PIPERAM', 'RG-BOPSTACK-BLINDRAM', 'RG-BOPSTACK-BONNET', 'RG-BOPSTACK-OPERATOR']);
rgc('RG-BOPSTACK-SPOOL', 'RG-BOPSTACK', 'well-control', 'Drilling spool with kill and choke outlets', ['drilling spool', 'spool outlets', 'side outlets (BOP)'], 'The flanged spool below the rams whose two side outlets take the kill line (pump in) and the choke line (flow out under control).', 'Outlets valved with a manual and a hydraulic valve each on full stacks; the choke line runs to the choke manifold.', 'API Spec 16A; rating with the stack.', 'Outlet valves tested with the stack.', ['RG-BOPSTACK-SPOOL', 'RG-BOPSTACK-SIDEOUTLET']);
rgc('RG-BOPSTACK-ADAPTER', 'RG-BOPSTACK', 'well-control', 'Adapter, bell nipple, and studs', ['BOP adapter', 'bell nipple', 'flow nipple', 'stack studs'], 'The crossover flange to the tubing head, the bell nipple on top that returns fluid to the flowline, and the stud sets between every flange.', 'Adapter matched to the tubing head flange; bell nipple sized to the pipe and the mud return rate.', 'Rated with the stack.', 'Studs made up to torque; the bell nipple is the H2S monitoring point.', ['RG-BOPSTACK-ADAPTER', 'RG-BOPSTACK-BELLNIPPLE', 'RG-BOPSTACK-STUDS'], { hazards: [H.pressure, H.h2s] });
rgc('RG-BOPSTACK-TUBINGHEADREF', 'RG-BOPSTACK', 'well-control', 'Tubing head (context)', ['tubing head (BOP context)'], 'The tubing head the stack sits on, shown translucent for context.', 'See the WH tubing head record.', 'None.', 'None.', ['RG-BOPSTACK-TUBINGHEAD'], { connections: [{ target: 'WH-TUBINGHEAD', direction: 'undirected', type: 'flanged' }] });
rg({ id: 'RG-ACCUMULATOR', parent: 'RG', group: 'well-control', level: 'equipment', name: 'Accumulator unit (closing unit)', aliases: ['BOP accumulator', 'closing unit', 'koomey', 'BOP control unit', 'BOP remote panel'], function: 'The hydraulic power unit with nitrogen-charged bottles that stores enough fluid to close every preventer and open one, operated from the driller\'s panel and a remote panel.', tabs: { overview: 'Pumps keep the bottles at system pressure; regulators set the annular and ram closing pressures; the remote panel sits away from the well so the stack can be closed from a safe distance.', engineering: 'Capacity and precharge per API Std 53; closing times tested.', safety: 'Precharge and drawdown tests; panel access kept clear.', evidence: EVR }, sources: ['S49', 'S9'], hazards: [H.pressure] });
rg({ id: 'RG-CHOKELINE', parent: 'RG', group: 'well-control', level: 'equipment', name: 'Choke manifold and kill line (workover)', aliases: ['workover choke manifold', 'kill line', 'choke line', 'well control manifold'], function: 'The manifold that takes a kick through an adjustable choke while the kill line pumps kill fluid: the same hardware family as the flowback choke manifold, plumbed to the stack outlets.', tabs: { overview: 'Choke line from the spool to the manifold; kill line from the pumps to the spool; gauges and a mud gas separator downstream on drilling rigs.', engineering: 'Rated with the stack; per API Std 53 arrangement.', safety: 'Lined up and tested before the stack is put to work.', evidence: EVR }, connections: [{ target: 'FB-CHOKEMANIFOLD', direction: 'undirected', type: 'flanged', note: 'same hardware family' }], sources: ['S49', 'S9'], hazards: [H.pressure] });
rg({ id: 'RG-STRIPPINGSTACK', parent: 'RG', group: 'well-control', level: 'equipment', name: 'Stripping and snubbing stack', aliases: ['stripping stack', 'snubbing BOPs', 'stripper rubber', 'safety head'], function: 'The stack of strippers and rams used to move pipe through a sealed wellhead under pressure on a snubbing job.', tabs: { overview: 'Two stripping rams or a stripper rubber alternate to pass connections; safety rams below for well control; equalizing loop between them.', engineering: 'Per API Std 53 for hydraulic workover; ratings with the well pressure.', safety: 'Sequenced closures; never both strippers open with pressure below.', evidence: EVR }, sources: ['S49', 'S53', 'S9'], hazards: [H.wellcontrol, H.pressure] });

// ================================================================ DA
const EVD = 'Field practice at the frac van and wellsite instrumentation (S9); pressure transducer practice (S31 missile patent for header instruments); no vendor data.';
const da = (o) => save({ status: 'draft', evidence_tier: 'E3', reviewers: [], system: 'DA', drawn_in_3d: false, sources: ['S9'], revision: rev('Drop 9 seed'), hazards: [H.electrical], tabs: { evidence: EVD }, ...o });
da({ id: 'DA', level: 'system', name: 'Data acquisition and monitoring', aliases: ['data acquisition', 'DA', 'instrumentation', 'monitoring', 'frac data'],
  function: 'The sensors, cabling, and displays that let the treater and the company representative see the job: surface pressure and rate, slurry density and proppant concentration, chemical rates, pump health, downhole gauges, fiber, and microseismic where used.',
  tabs: { overview: 'Every number on the simulator control panel exists as a sensor on the pad: transducers on the missile and the wellhead, flowmeters on the blender discharge, a densometer on the slurry line, chemical pump totalizers, and the pump and engine data over the fleet network. The frac van collects them and shows the treating plot. Offset wells carry gauges to watch for frac hits; some pads run fiber for distributed acoustic and temperature sensing, or microseismic arrays, to see where the fractures go.', engineering: 'Transducer ranges above the relief setting; densometer calibration with fluid density; data logged per stage and archived with the job report.', safety: 'Instrument power isolated at the sensor; cable trays and covers across walkways.', evidence: EVD, failure_modes: 'Transducer drift or plugging, densometer source faults, data dropouts on the fleet network.' }, hazards: [H.electrical] });
da({ id: 'DA-FRACVAN', parent: 'DA', group: 'surface', level: 'equipment', name: 'Frac van (data van) and the treating plot', aliases: ['treater van', 'treating plot', 'job plot', 'van (frac data)'], function: 'The control trailer where the treater runs the job: the treating plot of pressure, rate, and density against time, the pump controls, and the chemical setpoints.', tabs: { overview: 'The treating plot is the same picture as the simulator chart: surface pressure, slurry rate, and proppant concentration, with the kickout line. The treater watches the pressure trend for a screenout or a break, adjusts rate and sand, and calls the shutdown. Company representatives watch the same plot from a second seat.', engineering: 'One-second data; job logs per stage; redundant transducers averaged.', safety: 'The van sits outside the red zone; radios to the pumps and the wireline unit.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-DATAVAN', connections: [{ target: 'PP-DATAVAN', direction: 'undirected', type: 'data' }] });
da({ id: 'DA-TRANSDUCER', parent: 'DA', group: 'sensors', level: 'component', name: 'Pressure transducers (missile, wellhead, annulus)', aliases: ['pressure transducer', 'PT', 'wellhead pressure sensor', 'annulus pressure'], function: 'Strain-gauge transducers on the missile header, the wellhead (treating pressure), and the casing annulus that feed the plot and the kickout logic.', tabs: { overview: 'Two on the missile for the pump-side reading, one on the wellhead for the true treating pressure, one on the annulus to catch communication; ranges above the relief setting.', engineering: 'Calibrated before the job; hammer union or NPT mounts with an isolation valve.', safety: 'Replaced with the pumps off and the line bled.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-MISSILE-TRANSDUCER' });
da({ id: 'DA-FLOWMETER', parent: 'DA', group: 'sensors', level: 'component', name: 'Flowmeters (clean rate, slurry rate)', aliases: ['flowmeter', 'turbine meter', 'magnetic flowmeter', 'rate meter'], function: 'The turbine or magnetic meters on the blender suction (clean rate) and discharge (slurry rate) that give the treating rate.', tabs: { overview: 'Clean rate minus slurry rate gives the sand volume; the pump stroke counters give a cross-check.', engineering: 'Calibrated with the fluid; turbine meters foul with sand, magnetic meters do not.', safety: 'None beyond the lines.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-BLENDER' });
da({ id: 'DA-DENSOMETER', parent: 'DA', group: 'sensors', level: 'component', name: 'Densometer and proppant concentration', aliases: ['densometer', 'densitometer', 'nuclear densometer', 'PPA meter'], function: 'The density meter on the slurry line that reads slurry density and, with the clean fluid density, gives proppant concentration in pounds added per gallon.', tabs: { overview: 'Nuclear (gamma) or non-nuclear (Coriolis) types; the concentration on the plot comes from this reading, not from the sand screw setting.', engineering: 'Zeroed on clean fluid at the start of each stage.', safety: 'Nuclear sources are licensed and badged.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-BLENDER' });
da({ id: 'DA-CHEMTOTALIZER', parent: 'DA', group: 'sensors', level: 'component', name: 'Chemical rate meters and totalizers', aliases: ['chem totalizer', 'additive rate', 'FR rate', 'chemical meters'], function: 'The meters on each additive pump that report the rate and total of friction reducer, biocide, scale inhibitor, and the other chemicals against the program.', tabs: { overview: 'Setpoints in gallons per thousand gallons of clean fluid; the van compares delivered to designed.', engineering: 'Positive-displacement pump strokes or flowmeters per additive.', safety: 'Chemical handling per the data sheets.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-CHEMADD', hazards: [H.chem] });
da({ id: 'DA-PUMPMONITOR', parent: 'DA', group: 'sensors', level: 'component', name: 'Pump and fleet monitoring', aliases: ['pump monitoring', 'fleet data', 'engine data', 'fluid end monitoring'], function: 'The data from each pump (rate, discharge pressure, gear, engine load, fluid end vibration) over the fleet network to the van, used to balance the spread and catch a failing pump.', tabs: { overview: 'Each pump reports to the van; the treater sees which pump is in which gear and pulls one out of the lineup when its numbers drift.', engineering: 'Vendor telemetry; kickout setpoints pushed to each pump.', safety: 'None beyond the pumps.', evidence: EVD }, drawn_in_3d: true, scene: 'PP-FRACPUMP' });
da({ id: 'DA-OFFSETGAUGE', parent: 'DA', group: 'downhole', level: 'equipment', name: 'Offset well pressure gauges (frac hit monitoring)', aliases: ['offset gauge', 'frac hit monitoring', 'offset well pressure', 'parent well gauge'], function: 'Pressure gauges on the wellheads of neighboring wells (or downhole gauges in them) that show when a fracture reaches them.', tabs: { overview: 'A frac hit shows as a pressure rise on the offset while a stage is pumped; the treater and the engineer decide whether to change the schedule or protect the parent well.', engineering: 'Surface gauges on the tree; downhole gauges on wireline or the tubing where the well is shut in.', safety: 'Offset well valves confirmed closed before the frac.', evidence: EVD }, drawn_in_3d: true, scene: 'UC-PRODTREE-GAUGE' });
da({ id: 'DA-FIBER', parent: 'DA', group: 'downhole', level: 'equipment', name: 'Fiber optic sensing (DAS and DTS)', aliases: ['fiber', 'DAS', 'DTS', 'distributed acoustic sensing', 'distributed temperature sensing'], function: 'A fiber optic cable, cemented behind casing or run on wireline or coiled tubing, interrogated for acoustic energy and temperature along its length to show which clusters take fluid and where fractures cross.', tabs: { overview: 'Cluster efficiency, stage isolation, and frac hits show up in the data during and after the job; permanent installs also watch production.', engineering: 'Interrogator at surface; cable protected across the couplings; orientation to avoid perforating it.', safety: 'Laser sources at the interrogator.', evidence: EVD }, hazards: [] });
da({ id: 'DA-MICROSEISMIC', parent: 'DA', group: 'downhole', level: 'equipment', name: 'Microseismic monitoring', aliases: ['microseismic', 'geophone array', 'frac mapping'], function: 'Geophone arrays in an offset well or on surface that locate the small seismic events of fracture growth, mapping the treated volume in real time.', tabs: { overview: 'Used on pilot projects and spacing tests more than on routine pads; the event cloud shows fracture height, length, and azimuth against the well spacing.', engineering: 'Array depth and distance limit the detection; velocity model from logs.', safety: 'None beyond the monitor well.', evidence: EVD }, hazards: [] });

// ================================================================ MT
const EVM = 'PetroWiki fracturing fluids and additives (S50), propping agents (S51), API RP 19C (S52), API Spec 5CT (S27), API Spec 10A (S28), field practice (S9).';
const mt = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'MT', drawn_in_3d: false, sources: ['S50', 'S51', 'S9'], revision: rev('Drop 9 seed'), hazards: [H.chem], tabs: { evidence: EVM }, ...o });
mt({ id: 'MT', level: 'system', name: 'Materials and consumables', aliases: ['materials', 'consumables', 'MT', 'proppant and chemicals', 'frac chemicals'],
  function: 'What the job consumes: proppant, base fluid and its additives, cement, casing and tubing grades, and the elastomers and consumables in the tools.',
  tabs: { overview: 'Pad Setup picks the proppant type and intensity and the fluid system; these records explain the choices. Proppant is sized sand or ceramic chosen for the closure stress; the fluid is water with friction reducer (slickwater), viscosified with polymer (linear or crosslinked gel) where transport matters, plus biocide, scale inhibitor, surfactant, clay control, buffers, and breakers as the program calls for. Cement and casing grades are chosen for the well design, not the frac.', engineering: 'Proppant tested to API RP 19C; fluids qualified on rheology and breaker tests at bottomhole temperature; casing per API 5CT; cement per API 10A.', safety: 'Silica dust at the sand area; chemical handling at the additive unit; hot or reactive fluids in acid jobs.', evidence: EVM, failure_modes: 'Proppant crush and embedment, fluid gel damage to the pack, incompatible additives, bacterial souring from untreated water.' }, hazards: [H.dust, H.chem], sources: ['S50', 'S51', 'S52', 'S9'] });
mt({ id: 'MT-PROPPANT', parent: 'MT', group: 'proppant', level: 'equipment', name: 'Proppant: sand, resin-coated sand, ceramic', aliases: ['proppant', 'frac sand', '100 mesh', '40/70', '30/50', 'ceramic proppant', 'resin-coated sand', 'bauxite'],
  function: 'The sized granular material pumped into the fracture to hold it open: natural silica sand at low stress, resin-coated sand for strength and flowback control, intermediate strength ceramic and sintered bauxite at high closure stress.',
  tabs: { overview: 'Mesh names give the sieve range: 100 mesh is fine sand for far-field placement and lower bridging risk; 40/70 and 30/50 are coarser for near-wellbore conductivity. Fracture conductivity is propped width times pack permeability, and it falls with stress, crushing, embedment, and gel damage. Shale wells today pump mostly regional 100 mesh and 40/70 sand at high intensity; ceramics appear in deep, high-stress wells.', engineering: 'Tested per API RP 19C: sieve distribution, sphericity and roundness, acid solubility, crush at stress; conductivity from long-term conductivity tests.', safety: 'Respirable silica at every transfer point; enclosed systems, dust collection, and monitoring.', evidence: EVM, failure_modes: 'Crushed fines that plug the pack, embedment in soft rock, proppant flowback into the wellbore.' }, standards: [{ standard: 'API RP 19C', edition: 'verify', paraphrase: 'Proppant property measurement.', source: 'S52' }], hazards: [H.dust], sources: ['S51', 'S52', 'S9'] });
mt({ id: 'MT-FLUIDSYSTEMS', parent: 'MT', group: 'fluids', level: 'equipment', name: 'Fracturing fluid systems', aliases: ['frac fluid', 'slickwater', 'linear gel', 'crosslinked gel', 'hybrid fluid', 'HVFR', 'foam frac'],
  function: 'The base fluid designs: slickwater (water plus friction reducer), high-viscosity friction reducer systems, linear polymer gels, crosslinked gels, and the less common foam, oil-based, and acid-based fluids.',
  tabs: { overview: 'Slickwater carries sand by velocity and leaves the least damage; linear and crosslinked gels carry more sand at lower rates and need breakers to clean up; hybrids pump slickwater first and gel later. Pad Setup uses the fluid choice to set friction and screenout tolerance.', engineering: 'Viscosity at bottomhole temperature, friction pressure, proppant transport, and break time are the design tests.', safety: 'Chemical handling; hot crosslinked fluids in some systems.', evidence: EVM }, sources: ['S50', 'S9'] });
mt({ id: 'MT-FRICTIONREDUCER', parent: 'MT-FLUIDSYSTEMS', group: 'fluids', level: 'component', name: 'Friction reducer', aliases: ['FR', 'friction reducer', 'polyacrylamide'], function: 'The polyacrylamide additive that cuts pipe friction so high rates can be pumped at lower surface pressure; loaded higher for high-viscosity systems.', tabs: { overview: 'Emulsion or dry products metered at the additive unit; salt-tolerant grades for produced water.', engineering: 'Loading in gallons per thousand gallons; friction loop tests.', safety: 'Slippery spills.', evidence: EVM }, sources: ['S50'] });
mt({ id: 'MT-GELANDBREAKER', parent: 'MT-FLUIDSYSTEMS', group: 'fluids', level: 'component', name: 'Gelling agents, crosslinkers, and breakers', aliases: ['guar', 'gel', 'crosslinker', 'borate', 'breaker', 'oxidizer breaker', 'enzyme breaker'], function: 'The polymer (guar or derivatives) that viscosifies the fluid, the crosslinker (borate or metal) that builds a stronger gel, and the breaker (oxidizer or enzyme) that degrades it after placement.', tabs: { overview: 'Gel carries sand; crosslinked gel carries more at high temperature; the breaker returns the fluid to water so the pack cleans up. Too little breaker leaves damage; too much breaks the gel early.', engineering: 'Rheology and break tests at bottomhole temperature; pH buffers control the crosslink.', safety: 'Oxidizer handling.', evidence: EVM }, sources: ['S50'] });
mt({ id: 'MT-ADDITIVES', parent: 'MT-FLUIDSYSTEMS', group: 'fluids', level: 'component', name: 'Biocide, scale inhibitor, surfactant, clay control, buffers', aliases: ['biocide', 'scale inhibitor', 'surfactant', 'clay stabilizer', 'KCl', 'buffer', 'fluid loss additive'], function: 'The supporting additives: biocide against bacteria in the water, scale inhibitor against mineral deposits, surfactant for cleanup, clay stabilizer against swelling, buffers for pH, and fluid-loss additives where leakoff is high.', tabs: { overview: 'Small volumes metered continuously; the program sets each concentration per the water analysis and the formation.', engineering: 'Compatibility tested with the water and each other.', safety: 'Data sheets on site; biocides and acids are the hazardous ones.', evidence: EVM }, sources: ['S50'] });
mt({ id: 'MT-WATER', parent: 'MT', group: 'fluids', level: 'equipment', name: 'Frac water: fresh, brackish, produced, and recycled', aliases: ['frac water', 'source water', 'produced water reuse', 'recycled water', 'water quality'], function: 'The base water for the job from wells, ponds, pipelines, or recycled produced water, with its salinity, bacteria, iron, and solids set against the fluid design.', tabs: { overview: 'Volumes come from the fluid intensity in Pad Setup; salt-tolerant friction reducers let produced water be reused; bacteria and iron are treated at the pits or on the fly.', engineering: 'Water analysis before the job; chemistry adjusted per the analysis.', safety: 'Lay-flat lines across roads; pit liners and fencing.', evidence: EVM }, hazards: [] });
mt({ id: 'MT-CEMENT', parent: 'MT', group: 'cement', level: 'equipment', name: 'Cement classes and additives', aliases: ['oilwell cement', 'API cement class', 'Class H', 'Class G', 'cement additives'], function: 'The oilwell cements (API classes, commonly G and H on land) and the additives (retarders, accelerators, extenders, fluid-loss control, weighting agents) that place them across the intervals the casing design calls for.', tabs: { overview: 'The cement sheath in the CM records is these materials placed; the frac depends on it for stage isolation in cemented completions.', engineering: 'Per API Spec 10A; slurry design tested for thickening time and strength at downhole temperature.', safety: 'Cement dust and caustic slurry.', evidence: EVM }, standards: [{ standard: 'API Spec 10A', edition: 'verify', paraphrase: 'Cements and materials for well cementing.', source: 'S28' }], sources: ['S28', 'S9'], hazards: [H.chem] });
mt({ id: 'MT-CASINGGRADES', parent: 'MT', group: 'tubulars', level: 'equipment', name: 'Casing and tubing grades and connections', aliases: ['casing grade', 'P110', 'L80', 'tubing grade', 'steel grades', 'API connection'], function: 'The steel grades (API 5CT: J55, L80, N80, P110 and others) and connections (API round, buttress, premium) chosen for burst, collapse, tension, and sour service.', tabs: { overview: 'The production casing takes the frac pressure, so its burst rating sets the treating pressure ceiling with the tree; sour wells use restricted-yield grades; premium connections for gas tightness and high torque.', engineering: 'Per API Spec 5CT; design factors per the operator standard.', safety: 'None beyond handling.', evidence: EVM }, standards: [{ standard: 'API Spec 5CT', edition: 'verify', paraphrase: 'Casing and tubing grades, dimensions, and testing.', source: 'S27' }], sources: ['S27', 'S9'], hazards: [] });
mt({ id: 'MT-ELASTOMERS', parent: 'MT', group: 'consumables', level: 'equipment', name: 'Elastomers and consumables (seals, packing, grease, plug materials)', aliases: ['elastomers', 'seals', 'valve packing', 'valve grease', 'composite plug material', 'dissolvable alloy'], function: 'The wearing materials across the systems: valve seals and packing, wireline grease, BOP elements, plug composites and dissolvable alloys, and the lubricants that keep the iron cycling.', tabs: { overview: 'Chosen for temperature, fluids, and gas; the frac stack valves are greased every stage; plug materials set the drillout or dissolve time.', engineering: 'Material class per the service (standard, sour, high temperature).', safety: 'None beyond the equipment.', evidence: EVM }, hazards: [] });

console.log('seeded drop 9');
