// Drop 6 seed: UC (upper completion and production tree) and CM (casing and cementing). Every new record is "draft".
// Run: node scripts/seed-drop6.mjs
import fs from 'node:fs';
import path from 'node:path';

const DATE = '2026-09-29';
const rev = (note) => ({ rev: 'A', author: 'AI draft', date: DATE, note });
const REC = (sys) => path.resolve('content/records', sys);
const load = (sys, id) => JSON.parse(fs.readFileSync(path.join(REC(sys), id + '.json'), 'utf8'));
const save = (r) => { fs.mkdirSync(REC(r.system), { recursive: true }); fs.writeFileSync(path.join(REC(r.system), r.id + '.json'), JSON.stringify(r, null, 2) + '\n'); };
const H = {
  pressure: { class: 'Stored pressure', control: 'Pressure test before opening to the well; bleed down and verify zero before breaking any connection.' },
  lof: { class: 'Line of fire', control: 'Stay clear of flowlines and iron under flow; restraints on temporary lines.' },
  pinch: { class: 'Pinch point', control: 'Hands clear of handwheels, elevators, and tongs.' },
  dropped: { class: 'Dropped object', control: 'Certified lifting gear; casing and tubing handling by trained crews.' },
  h2s: { class: 'H2S', control: 'Monitors at the tree and flowline; escape sets staged.' },
  fire: { class: 'Fire and flammable gas', control: 'No ignition sources at the tree; grounding on the flowline.' },
  cement: { class: 'Cement and chemicals', control: 'Eye and skin protection at the cementing unit; dust controls at bulk transfer.' },
};

// ---- sources
const srcPath = path.resolve('content/sources.json');
const sources = JSON.parse(fs.readFileSync(srcPath, 'utf8'));
const add = (s) => { if (!sources.find(x => x.id === s.id)) sources.push(s); };
add({ id: 'S27', title: 'API Spec 5CT, Casing and Tubing', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S28', title: 'API Spec 10A, Cements and Materials for Well Cementing', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S29', title: 'API Spec 14A, Subsurface Safety Valve Equipment', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
add({ id: 'S30', title: 'API RP 10D-2, Centralizer Placement and Stop Collar Testing', publisher: 'American Petroleum Institute', edition: 'verify edition held', access: 'Paid standard', tier: 'E1', url: '' });
fs.writeFileSync(srcPath, JSON.stringify(sources, null, 2) + '\n');

// ---- glossary
const gPath = path.resolve('content/glossary.json');
const glossary = JSON.parse(fs.readFileSync(gPath, 'utf8'));
const gadd = (g) => { const i = glossary.findIndex(x => x.term === g.term); if (i >= 0) glossary[i] = g; else glossary.push(g); };
gadd({ term: 'Production tree', aliases: ['Christmas tree', 'prod tree', 'flowing tree'], system: 'UC', record: 'UC-PRODTREE', definition: 'The permanent valve assembly set on the tubing head after the completion: masters, flow cross, wing valves, choke, and swab valve that control the producing well.' });
gadd({ term: 'Float shoe and float collar', aliases: ['guide shoe', 'float equipment', 'shoe track'], system: 'CM', record: 'CM-WELLBORE-SHOE', definition: 'The check-valve fittings at the bottom of a casing string that guide it into the hole and keep cement from flowing back up the casing after the job.' });
gadd({ term: 'Cement sheath', aliases: ['annular cement', 'top of cement', 'TOC'], system: 'CM', record: 'CM-WELLBORE-CEMENT', definition: 'The cement placed in the annulus between the casing and the hole (or the previous casing) that supports the string and isolates the formations behind it.' });
gadd({ term: 'Subsurface safety valve', aliases: ['SSSV', 'SCSSV', 'downhole safety valve'], system: 'UC', record: 'UC-SSSV', definition: 'The fail-closed valve in the tubing below the wellhead that shuts the well in if surface control pressure is lost.' });
fs.writeFileSync(gPath, JSON.stringify(glossary, null, 2) + '\n');

// ================================================================ UC system
const EVU = 'API 6A scope for trees (S1), API Spec 14A for safety valves (S29), API 11D1 for packers (S21), field practice (S9). Photographs read for proportion only.';
const UC_GLB = '/glb/UC/UC-PRODTREE.glb';
const uc = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'UC', drawn_in_3d: false, sources: ['S1', 'S9'], revision: rev('Drop 6 seed'), hazards: [H.pressure], ...o });
const ucc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => uc({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVU, ...(extra.tabs || {}) }, drawn_in_3d: !!nodes, ...(nodes ? { glb: UC_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

uc({ id: 'UC', level: 'system', name: 'Upper completion and production tree', aliases: ['upper completion', 'production tree', 'tubing completion', 'final completion'],
  function: 'The permanent equipment that turns the fractured wellbore into a producing well: the tubing string with its packer, safety valve, and accessories hung in the tubing head, and the production tree on top that controls flow to the flowline.',
  tabs: {
    overview: 'Once the frac stack comes off, the well is completed for production. Tubing is run with a production packer (or landed open-ended for early flowback on many shale wells), a subsurface safety valve where required, landing nipples, and a seal assembly, and is hung in the tubing head on a tubing hanger. The production tree is bolted onto the tubing head adapter: lower and upper master valves, a flow cross, a production wing with a choke to the flowline, a kill wing, a swab valve, and a cap with a gauge. Artificial lift, when needed, is installed later through the same tree.',
    engineering: 'Tree rating and bore follow API 6A (a 3-1/16 in. 10K tree is common on shale wells); tubing per API 5CT; the safety valve per API 14A where the regulator or operator requires it; packers per API 11D1.',
    connections: 'Tubing hanger in the tubing head (WH); flowline from the wing to the facility; control line to the safety valve; casing annulus outlets on the tubing head.',
    safety: 'The tree is the permanent pressure boundary; valve stems and handwheels are the pinch points; H2S and flammable gas at the tree and flowline.',
    specs: 'Tree 3-1/16 in. 10K typical; tubing 2-7/8 in. typical on shale wells; packer and SSSV ratings per the well.',
    evidence: EVU, operations: 'Installed after the drillout and initial flowback, or before flowback where the tubing is needed to lift the well.',
    failure_modes: 'Tree valve seat leaks, choke erosion, tubing leaks, packer seal failure, safety valve failing to close or to hold.',
  }, standards: [{ standard: 'API Spec 6A', edition: 'verify', paraphrase: 'Wellhead and tree equipment: ratings, materials, testing.', source: 'S1' }, { standard: 'API Spec 14A', edition: 'verify', paraphrase: 'Subsurface safety valve equipment qualification.', source: 'S29' }],
  hazards: [H.pressure, H.pinch, H.h2s, H.fire], sources: ['S1', 'S9', 'S29', 'S21'] });

uc({ id: 'UC-PRODTREE', parent: 'UC', group: 'production-tree', level: 'equipment', name: 'Production tree (3-1/16 in. 10K)', aliases: ['production tree', 'Christmas tree', 'flowing tree', 'prod tree'],
  function: 'The permanent stack of valves on the tubing head adapter that controls the producing well: masters, flow cross, wing valve and choke to the flowline, kill wing, swab valve, and cap.',
  tabs: {
    overview: 'Bottom to top: tubing head adapter, lower master valve (manual, the barrier valve, left open and not cycled), upper master valve (manual on this tree, hydraulic on some), studded flow cross, production wing valve (manual) feeding an adjustable choke with an electric actuator and the flowline flange, kill wing valve (manual) with a companion flange and a gauge, swab valve (manual), and a tree cap with a needle valve and pressure gauge. Stems point to one side so the operator works from a single position.',
    engineering: 'Smaller and simpler than the frac stack: 3-1/16 in. bore is enough for production rates and wireline work, and manual valves suit a well visited weekly. The choke actuator lets the facility control the rate remotely. The kill wing accepts a pump truck for a kill or a treatment.',
    connections: 'Tubing head adapter below; flowline from the choke outlet; kill line on the kill wing when needed; gauge and sensor ports.',
    safety: 'Permanent pressure boundary; H2S monitors; handwheels are pinch points; the swab valve is opened only with a lubricator on the cap.',
    specs: '3-1/16 in. 10K typical; valves API 6A; choke sized in 64ths.',
    evidence: EVU, operations: 'Set once; valves greased and cycled on a maintenance schedule; the choke is the working control.',
    failure_modes: 'Seat leaks, packing leaks, choke erosion, actuator faults, gauge failures.',
  }, drawn_in_3d: true, glb: UC_GLB,
  mesh_nodes: ['UC-PRODTREE-TUBINGHEADADAPTER', 'UC-PRODTREE-LMV', 'UC-PRODTREE-UMV', 'UC-PRODTREE-FLOWCROSS', 'UC-PRODTREE-WINGVALVE', 'UC-PRODTREE-CHOKE', 'UC-PRODTREE-ACTUATOR', 'UC-PRODTREE-FLOWLINE', 'UC-PRODTREE-KILLWING', 'UC-PRODTREE-GAUGE', 'UC-PRODTREE-SWAB', 'UC-PRODTREE-TREECAP', 'UC-PRODTREE-STUDS'],
  connections: [{ target: 'WH-TUBINGHEAD', direction: 'upstream', type: 'flanged', rating: '10K' }, { target: 'UC-FLOWLINE', direction: 'downstream', type: 'flanged' }], hazards: [H.pressure, H.pinch, H.h2s] });
ucc('UC-PRODTREE-TUBINGHEADADAPTER', 'UC-PRODTREE', 'production-tree', 'Tubing head adapter', ['adapter', 'tubing bonnet', 'tree adapter (production)'], 'The crossover between the tubing head and the tree that seals on the tubing hanger neck and carries the tree.', 'Flanged below to the tubing head and above to the lower master; seals on the hanger extended neck so the tubing pressure is isolated from the annulus.', 'API 6A; rating matched to the tree.', 'Tested with the tree before the well is opened.', ['UC-PRODTREE-TUBINGHEADADAPTER']);
ucc('UC-PRODTREE-LMV', 'UC-PRODTREE', 'production-tree', 'Lower master valve', ['LMV (production)', 'master valve'], 'The barrier valve at the bottom of the tree, left open in service and closed only when the tree above it needs work.', 'Manual gate valve; not cycled under flow so the seats stay unworn for the day it must hold.', 'API 6A; same rating as the tree.', 'Cycled only with the well shut in on the upper master.', ['UC-PRODTREE-LMV']);
ucc('UC-PRODTREE-UMV', 'UC-PRODTREE', 'production-tree', 'Upper master valve', ['UMV (production)', 'working master'], 'The working master valve, cycled to shut the well in; hydraulic with a surface safety system on some trees.', 'Manual on this tree; a hydraulic actuator with a fail-closed spring makes it a surface safety valve where required.', 'API 6A.', 'The valve used for routine shut-ins so the lower master stays fresh.', ['UC-PRODTREE-UMV']);
ucc('UC-PRODTREE-FLOWCROSS', 'UC-PRODTREE', 'production-tree', 'Flow cross', ['tree cross', 'flow tee', 'studded cross (production)'], 'The studded block with the vertical bore and two side outlets for the production and kill wings.', 'Cross with flanged outlets; a tee is used where only one wing is needed.', 'API 6A.', 'Erosion checks at the outlet turns.', ['UC-PRODTREE-FLOWCROSS']);
ucc('UC-PRODTREE-WINGVALVE', 'UC-PRODTREE', 'production-tree', 'Production wing valve', ['wing valve (production)', 'flow wing', 'flowline valve'], 'The valve on the production side of the cross, upstream of the choke, that isolates the flowline from the well.', 'Manual gate valve; a hydraulic wing is used where a surface safety system shuts the flowline.', 'API 6A.', 'Closed to work on the choke or flowline.', ['UC-PRODTREE-WINGVALVE']);
ucc('UC-PRODTREE-CHOKE', 'UC-PRODTREE', 'production-tree', 'Wellhead choke (adjustable)', ['choke (production)', 'wellhead choke', 'adjustable choke (tree)'], 'The adjustable choke on the production wing that sets the flow rate and takes the pressure drop from tubing pressure to flowline pressure.', 'A needle and seat or a cage type; erosion-resistant trim; the bean size sets the rate and is read in 64ths.', 'Sized per the flowline and separator pressures.', 'Erosion; flowline pressure rises if the choke fails open.', ['UC-PRODTREE-CHOKE']);
ucc('UC-PRODTREE-ACTUATOR', 'UC-PRODTREE-CHOKE', 'production-tree', 'Choke actuator', ['electric actuator', 'choke motor', 'remote choke'], 'The electric actuator on the choke stem that lets the facility set the choke remotely and follow a rate or pressure setpoint.', 'Solar-powered on remote pads; position feedback to the SCADA system; manual override handwheel.', 'Per the automation design.', 'Electrical isolation before service.', ['UC-PRODTREE-ACTUATOR']);
ucc('UC-PRODTREE-FLOWLINE', 'UC-PRODTREE', 'production-tree', 'Flowline connection', ['flowline', 'flowline riser', 'production line'], 'The flanged elbow and drop leg that takes flow from the choke down to the buried flowline toward the facility.', 'Flanged to the choke; drops to grade and runs to the header or the separator; check valve and pressure sensor on the line.', 'Flowline class per the facility design.', 'Line of fire under flow; grounding.', ['UC-PRODTREE-FLOWLINE'], { hazards: [H.lof, H.fire] });
ucc('UC-PRODTREE-KILLWING', 'UC-PRODTREE', 'production-tree', 'Kill wing valve', ['kill wing', 'kill valve', 'pump-in wing'], 'The valve on the opposite side of the cross with a companion flange, used to pump into the tubing for a kill, a treatment, or a pressure test.', 'Manual gate valve; the companion flange is blind between jobs with a gauge or a needle valve on it.', 'API 6A.', 'Blind flange and gauge inspected with the tree.', ['UC-PRODTREE-KILLWING']);
ucc('UC-PRODTREE-SWAB', 'UC-PRODTREE', 'production-tree', 'Swab valve (production)', ['swab valve (tree)', 'crown valve (production)'], 'The top valve of the tree, closed in service, opened only when a lubricator is on the cap for wireline or slickline work.', 'Manual gate valve.', 'API 6A.', 'Lubricator tested before the swab is opened.', ['UC-PRODTREE-SWAB']);
ucc('UC-PRODTREE-TREECAP', 'UC-PRODTREE', 'production-tree', 'Tree cap', ['tree cap', 'top connection', 'cap'], 'The cap on the swab valve carrying a needle valve and a pressure gauge; removed to fit a lubricator.', 'Flanged or threaded cap with a gauge port and a lubricator profile.', 'API 6A.', 'Bled through the needle valve before removal.', ['UC-PRODTREE-TREECAP']);
ucc('UC-PRODTREE-GAUGE', 'UC-PRODTREE', 'production-tree', 'Gauges and needle valves', ['gauge', 'tubing pressure gauge', 'needle valve'], 'The gauges on the cap and the kill wing reading tubing pressure, each behind a needle valve.', 'Bourdon gauge or transducer; needle valve for isolation.', 'Range per the tree rating.', 'Needle valve closed before a gauge is changed.', ['UC-PRODTREE-GAUGE']);
{
  const r = load('WH', 'WH-STUDBOLTS');
  r.tabs.overview = (r.tabs.overview || '') + ' The production tree model carries its own stud sets as UC-PRODTREE-STUDS.';
  save(r);
}
uc({ id: 'UC-PRODTREE-STUDSREF', parent: 'UC-PRODTREE', group: 'production-tree', level: 'component', name: 'Stud and nut sets (production tree)', aliases: ['tree studs', 'flange studs (production)'],
  function: 'The stud and nut sets between every flange of the production tree; the same hardware family as the frac stack.',
  tabs: { overview: 'One node in the model for all the stud sets; see the wellhead stud bolt record for materials and make-up practice.', engineering: 'Per API 6A; sized to the flange.', safety: 'Made up to the specified torque or stretch.', evidence: EVU },
  drawn_in_3d: true, glb: UC_GLB, mesh_nodes: ['UC-PRODTREE-STUDS'], connections: [{ target: 'WH-STUDBOLTS', direction: 'undirected', type: 'mechanical', note: 'Same hardware family' }] });

uc({ id: 'UC-TUBING', parent: 'UC', group: 'tubing-string', level: 'equipment', name: 'Production tubing string', aliases: ['tubing', 'production tubing', 'tubing string', '2-7/8 tubing'],
  function: 'The string of tubing hung from the tubing hanger that carries production from the reservoir to the tree, protecting the casing from produced fluids and giving a controlled flow path for artificial lift.',
  tabs: { overview: 'Run joint by joint with a workover rig or a snubbing unit after the frac and drillout, with the packer, safety valve, and nipples made up in it. On many shale wells the tubing is landed above the top perforations without a packer for early production, and a packer is added later.', engineering: 'Per API 5CT: size, weight, grade, and connection chosen for the pressure, the fluids, and the lift method; 2-7/8 in. is common on shale wells.', connections: 'Tubing hanger above; packer or open end below; nipples and safety valve in the string.', safety: 'Pipe handling; well control while running tubing in a live well.', evidence: EVU, operations: 'Run once; pulled for workovers.', failure_modes: 'Corrosion, connection leaks, erosion at the bottom, parted tubing.' }, standards: [{ standard: 'API Spec 5CT', edition: 'verify', paraphrase: 'Casing and tubing dimensions, grades, and testing.', source: 'S27' }], hazards: [H.dropped, H.pinch, H.pressure], sources: ['S27', 'S9'] });
uc({ id: 'UC-PACKER', parent: 'UC', group: 'tubing-string', level: 'equipment', name: 'Production packer', aliases: ['packer', 'production packer', 'permanent packer', 'retrievable packer'],
  function: 'The downhole seal between the tubing and the casing above the perforations that isolates the annulus from produced fluids and pressure.',
  tabs: { overview: 'Set hydraulically or mechanically; a permanent packer is milled out, a retrievable packer is released and pulled. The tubing lands in it through a seal assembly so the tubing can move with temperature.', engineering: 'Per API 11D1 validation grades; rating for differential from above and below; elastomers for the fluids and temperature.', connections: 'Tubing above through the seal assembly; casing wall.', safety: 'Annulus pressure monitoring shows a packer leak.', evidence: EVU, operations: 'Set once the tubing is landed; tested from the annulus.', failure_modes: 'Element leaks, slips not holding, seal assembly leaks.' }, standards: [{ standard: 'API Spec 11D1', edition: 'verify', paraphrase: 'Packer and bridge plug validation grades.', source: 'S21' }], sources: ['S21', 'S9'] });
uc({ id: 'UC-SEALASSEMBLY', parent: 'UC-PACKER', group: 'tubing-string', level: 'component', name: 'Seal assembly and polished bore', aliases: ['seal assembly', 'seal stack', 'polished bore receptacle', 'PBR'], drawn_in_3d: false,
  function: 'The stack of seals on the tubing that lands in the packer bore and seals while allowing tubing movement.',
  tabs: { overview: 'Seal units on a mandrel stab into the packer or a polished bore receptacle; the length of the bore allows the tubing to expand and contract without unseating.', engineering: 'Seal material for the fluids and temperature; stroke length per the thermal calculation.', safety: 'A leaking seal shows as annulus pressure.', evidence: EVU } });
uc({ id: 'UC-SSSV', parent: 'UC', group: 'tubing-string', level: 'equipment', name: 'Subsurface safety valve', aliases: ['SSSV', 'SCSSV', 'downhole safety valve', 'safety valve'],
  function: 'The fail-closed flapper valve in the tubing a few hundred feet below surface, held open by hydraulic control pressure from surface and closing on loss of that pressure.',
  tabs: { overview: 'Required offshore and on some land wells near people or infrastructure. A control line from a wellhead panel holds a piston against a spring; losing pressure (a fire, a line break, or a manual trip) lets the flapper close on flow. Tubing-retrievable valves are part of the string; wireline-retrievable valves land in a nipple.', engineering: 'Per API Spec 14A; setting depth, closing time, and leak rate tested; control line rated to the setting pressure plus margin.', connections: 'In the tubing string; control line to the tree panel.', safety: 'Function tested on a schedule; the tree panel is part of the safety system.', evidence: EVU, operations: 'Tested at commissioning and periodically.', failure_modes: 'Flapper leaks, control line leaks, failure to close.' }, standards: [{ standard: 'API Spec 14A', edition: 'verify', paraphrase: 'Subsurface safety valve design validation and functional testing.', source: 'S29' }], sources: ['S29', 'S9'] });
uc({ id: 'UC-NIPPLE', parent: 'UC', group: 'tubing-string', level: 'component', name: 'Landing nipples and profiles', aliases: ['landing nipple', 'profile nipple', 'no-go nipple', 'X nipple'], drawn_in_3d: false,
  function: 'Short profiled subs in the tubing string where wireline-set plugs, chokes, and safety valves can be locked and sealed.',
  tabs: { overview: 'Placed at planned depths: below the safety valve, above the packer, at the tail. A lock mandrel run on slickline latches in the profile; a no-go profile stops tools from passing.', engineering: 'Profile size stepped so tools reach the intended nipple; pressure rating with the tubing.', safety: 'Plugs set in nipples are barriers for tree work.', evidence: EVU } });
uc({ id: 'UC-SLIDINGSLEEVE', parent: 'UC', group: 'tubing-string', level: 'component', name: 'Sliding sleeve (production)', aliases: ['sliding sleeve', 'sliding side door', 'SSD', 'circulating sleeve'], drawn_in_3d: false,
  function: 'A tubing sub with ports covered by an inner sleeve that slickline shifts open to circulate between the tubing and the annulus, used to kill, unload, or displace the well.',
  tabs: { overview: 'Shifted with a slickline tool; closed in normal production. Different from the frac sleeve in the casing.', engineering: 'Rated with the tubing; seals inspected at workovers.', safety: 'Left closed and confirmed before pressure work.', evidence: EVU } });
uc({ id: 'UC-FLOWLINE', parent: 'UC', group: 'surface', level: 'equipment', name: 'Flowline to the facility', aliases: ['flowline', 'gathering line', 'production flowline'],
  function: 'The buried or surface line from the tree choke to the production facility or gathering header, with its check valve, sensors, and emergency shutdown valve.',
  tabs: { overview: 'Sized for the expected rate and the flowline pressure; a pressure transmitter and high-low pressure switches trip the wing or the ESD valve; pigging connections where waxes or solids build up.', engineering: 'Pipe class per the facility; corrosion inhibition where needed.', connections: 'Tree choke outlet; facility inlet header.', safety: 'Line of fire under flow; ESD tested.', evidence: EVU, operations: 'Commissioned with the tree; pigged as needed.', failure_modes: 'Corrosion, freezing, wax or scale, sensor faults.' }, hazards: [H.lof, H.fire] });

// ================================================================ CM system
const EVM = 'API Spec 5CT (S27), API Spec 10A (S28), API RP 10D-2 (S30), field practice (S9). Sizes are public nominal values; the schematic depth is not to scale.';
const CM_GLB = '/glb/CM/CM-WELLBORE.glb';
const cm = (o) => save({ status: 'draft', evidence_tier: 'E2', reviewers: [], system: 'CM', drawn_in_3d: false, sources: ['S27', 'S28', 'S9'], revision: rev('Drop 6 seed'), hazards: [H.dropped, H.pressure], ...o });
const cmc = (id, parent, group, name, aliases, fn, over, eng, safety, nodes, extra = {}) => cm({ id, parent, group, level: 'component', name, aliases, function: fn, tabs: { overview: over, engineering: eng, safety, evidence: EVM, ...(extra.tabs || {}) }, drawn_in_3d: !!nodes, ...(nodes ? { glb: CM_GLB, mesh_nodes: nodes } : {}), ...Object.fromEntries(Object.entries(extra).filter(([k]) => k !== 'tabs')) });

cm({ id: 'CM', level: 'system', name: 'Casing and cementing', aliases: ['casing', 'cementing', 'well construction', 'casing program'],
  function: 'The steel casing strings and the cement that build the wellbore the completion works in: they hold the hole open, isolate formations from each other and from the surface, and give the frac stack and the plugs something to seal against.',
  tabs: {
    overview: 'Each hole section is drilled, then a casing string is run and cemented: conductor near surface, surface casing below the freshwater zones, intermediate casing through troublesome formations, and production casing through the lateral. Cement is pumped down the casing and up the annulus with wiper plugs ahead and behind it; float equipment at the shoe keeps it from flowing back. The production casing is what the frac treatments are pumped through and what the frac plugs set in, so its burst rating, drift, and cement quality set what the completion can do.',
    engineering: 'Casing per API 5CT: size, weight, grade, connection; cement per API 10A with additives for the temperature and the slurry design; centralizers per API RP 10D-2 so the cement sheath is uniform. Burst, collapse, and tension are checked for the frac loads, not only the drilling loads.',
    connections: 'Casing strings hang in the wellhead (WH); the production casing bore is the frac flow path and the plug setting surface (DT).',
    safety: 'Casing handling and running; cement chemicals; well control during cementing.',
    specs: 'Common shale well: 13-3/8 in. surface, 9-5/8 in. intermediate, 5-1/2 in. production casing (schematic sizes in the model).',
    evidence: EVM, operations: 'Done by the drilling rig before the completion; the completion inherits the casing test and the cement evaluation.',
    failure_modes: 'Poor cement bond, channeling, casing wear from drilling, connection leaks, collapse during the frac.',
  }, standards: [{ standard: 'API Spec 5CT', edition: 'verify', paraphrase: 'Casing and tubing dimensions, grades, and testing.', source: 'S27' }, { standard: 'API Spec 10A', edition: 'verify', paraphrase: 'Well cement classes and testing.', source: 'S28' }, { standard: 'API RP 10D-2', edition: 'verify', paraphrase: 'Centralizer placement and stop collar testing.', source: 'S30' }],
  hazards: [H.dropped, H.pressure, H.cement], sources: ['S27', 'S28', 'S30', 'S9'] });

cm({ id: 'CM-WELLBORE', parent: 'CM', group: 'wellbore', level: 'equipment', name: 'Cased wellbore (schematic cut-away)', aliases: ['wellbore schematic', 'casing schematic', 'well schematic'],
  function: 'The teaching model of the cased vertical wellbore: four nested casing strings with their cement sheaths, float collars, shoes, and centralizers inside a translucent formation, with the depth compressed so every string is visible.',
  tabs: {
    overview: 'Use the section tool to open the wellbore. From the outside in: conductor, surface casing, intermediate casing, production casing. Each string ends in a guide shoe with a float collar one joint above it; centralizers sit above the shoe and where the string passes the previous shoe. Cement fills the annulus from the shoe up to the top of cement, which reaches surface on the outer strings and stops partway up on the inner ones. The wellhead sits at the top where the strings hang.',
    engineering: 'Diameters are the public nominal sizes 20, 13-3/8, 9-5/8, and 5-1/2 in.; depths are schematic. Nothing here is a well design.',
    connections: 'Wellhead (WH) at the top; the production casing continues into the lateral shown in the simulator downhole view.',
    safety: 'None; a teaching model.', evidence: EVM, operations: 'Reference for the completion crew: what the tree, plugs, and perforations sit in.', failure_modes: 'See the component records.',
  }, drawn_in_3d: true, glb: CM_GLB, ghost_nodes: ['CM-WELLBORE-FORMATION'],
  mesh_nodes: ['CM-WELLBORE-FORMATION', 'CM-WELLBORE-CONDUCTOR', 'CM-WELLBORE-SURFACECASING', 'CM-WELLBORE-INTERMEDIATECASING', 'CM-WELLBORE-PRODUCTIONCASING', 'CM-WELLBORE-CEMENT', 'CM-WELLBORE-SHOE', 'CM-WELLBORE-FLOATCOLLAR', 'CM-WELLBORE-CENTRALIZER', 'CM-WELLBORE-WELLHEAD'], hazards: [H.pressure] });
cmc('CM-WELLBORE-FORMATION', 'CM-WELLBORE', 'wellbore', 'Formation (context)', ['rock', 'overburden', 'formation'], 'The rock around the wellbore, drawn translucent so the casing strings can be seen.', 'Each hole section is drilled through it at the hole size shown; the cement bonds to it.', 'Not applicable.', 'None.', ['CM-WELLBORE-FORMATION']);
cmc('CM-WELLBORE-CONDUCTOR', 'CM-WELLBORE', 'wellbore', 'Conductor casing', ['conductor', 'drive pipe', 'conductor pipe'], 'The large, shallow first string that keeps the loose surface soil from caving and carries the returns to the pits while the surface hole is drilled.', 'Driven or cemented; 16 to 30 in. common; not a pressure string.', 'Per API 5CT or line pipe.', 'Pipe handling.', ['CM-WELLBORE-CONDUCTOR']);
cmc('CM-WELLBORE-SURFACECASING', 'CM-WELLBORE', 'wellbore', 'Surface casing', ['surface casing', 'surface string', '13-3/8 casing'], 'The string set below the freshwater aquifers and cemented to surface; it carries the wellhead and the BOP during drilling.', 'Depth set by regulation to protect fresh water; cemented to surface; the casing head is welded or threaded onto it.', 'Per API 5CT; cement to surface per regulation.', 'The regulatory string; cement returns to surface are confirmed.', ['CM-WELLBORE-SURFACECASING']);
cmc('CM-WELLBORE-INTERMEDIATECASING', 'CM-WELLBORE', 'wellbore', 'Intermediate casing', ['intermediate casing', 'intermediate string', '9-5/8 casing'], 'The string set through formations that would otherwise cause trouble while drilling the production hole: lost circulation, salt, high pressure, or unstable shale.', 'One or more intermediate strings depending on the well; cemented at least across the zones of concern.', 'Per API 5CT.', 'Wear from drilling the next section is checked before the frac.', ['CM-WELLBORE-INTERMEDIATECASING']);
cmc('CM-WELLBORE-PRODUCTIONCASING', 'CM-WELLBORE', 'wellbore', 'Production casing', ['production casing', 'production string', '5-1/2 casing', 'long string'], 'The string run to total depth through the lateral, cemented across the pay, and used as the frac conduit: treatments are pumped through it and the frac plugs seal in it.', 'Burst rating checked for the frac treating pressure plus margin; drift diameter sets the plug and tool sizes; premium or semi-premium connections for the pressure cycles; cement quality across the lateral sets stage isolation.', 'Per API 5CT; 5-1/2 in. 20 lb/ft P110 class is common on shale wells.', 'Casing test before the frac; wear and connection leaks are the failure modes that stop a job.', ['CM-WELLBORE-PRODUCTIONCASING'], { specs: [{ name: 'Typical production casing', value: '5-1/2 in. 20 lb/ft', unit: '', tier: 'E3', source: 'S9' }] });
cmc('CM-WELLBORE-CEMENT', 'CM-WELLBORE', 'wellbore', 'Cement sheath', ['cement', 'annular cement', 'primary cement', 'top of cement'], 'The set cement in the annulus between each casing string and the hole or the previous casing, supporting the string and isolating the formations behind it.', 'Slurry per API 10A class and additives; placed by displacement with plugs; top of cement set by the design and confirmed by a bond log or a temperature survey. Channels or a poor bond let frac stages communicate behind pipe.', 'API 10A cements; density and thickening time per the well.', 'Cement chemicals at the unit.', ['CM-WELLBORE-CEMENT'], { hazards: [H.cement] });
cmc('CM-WELLBORE-SHOE', 'CM-WELLBORE', 'wellbore', 'Guide shoe and float shoe', ['guide shoe', 'float shoe', 'shoe'], 'The rounded fitting at the bottom of each string that guides it past ledges and, as a float shoe, carries a check valve that keeps cement from flowing back up the casing.', 'Drillable body; the check valve holds the cement column until it sets; the shoe track between the float collar and the shoe is left full of cement.', 'Drillable materials; ratings per the string.', 'Float failure shows as cement flowing back when the pumps stop.', ['CM-WELLBORE-SHOE']);
cmc('CM-WELLBORE-FLOATCOLLAR', 'CM-WELLBORE', 'wellbore', 'Float collar', ['float collar', 'collar', 'landing collar'], 'The check-valve collar one or two joints above the shoe that the wiper plugs land on and that backs up the shoe valve.', 'Drillable; the top plug bumps on it and the pressure rise confirms the displacement is complete.', 'Drillable materials.', 'Plug bump pressure held then bled to check the floats.', ['CM-WELLBORE-FLOATCOLLAR']);
cmc('CM-WELLBORE-CENTRALIZER', 'CM-WELLBORE', 'wellbore', 'Centralizers', ['centralizer', 'bow-spring centralizer', 'rigid centralizer', 'stop collar'], 'The bow-spring or rigid devices on the casing that hold it away from the hole wall so the cement can surround the pipe evenly.', 'Placement per API RP 10D-2: near the shoe, across the pay, and where the standoff matters; bow springs for open hole, rigid types in casing.', 'Per API RP 10D-2 and the standoff calculation.', 'Sharp edges when handling.', ['CM-WELLBORE-CENTRALIZER'], { standards: [{ standard: 'API RP 10D-2', edition: 'verify', paraphrase: 'Centralizer placement and stop collar testing.', source: 'S30' }] });
cmc('CM-WELLBORE-WELLHEAD', 'CM-WELLBORE', 'wellbore', 'Wellhead (context)', ['wellhead stub'], 'The wellhead stack at surface where the casing strings hang; see the WH system for the full model.', 'Casing head on the surface casing; spools for each string.', 'Per API 6A.', 'See WH.', ['CM-WELLBORE-WELLHEAD'], { connections: [{ target: 'WH-CASINGHEAD', direction: 'undirected', type: 'mechanical', note: 'Full wellhead model' }] });
cm({ id: 'CM-CEMENTHEAD', parent: 'CM', group: 'cementing', level: 'equipment', name: 'Cementing head and wiper plugs', aliases: ['cement head', 'plug container', 'wiper plugs', 'bottom plug', 'top plug'],
  function: 'The head on top of the casing during a cement job that holds the bottom and top wiper plugs and releases them ahead of and behind the cement.',
  tabs: { overview: 'The bottom plug wipes mud ahead of the cement and ruptures at the float collar; the top plug separates cement from the displacement fluid and bumps on the collar to signal the end of displacement. Plug release is confirmed by indicators on the head.', engineering: 'Rated for the pump pressure; plug sizes per the casing.', connections: 'Casing below; cement unit line in.', safety: 'High-pressure connections; plug release confirmed remotely.', evidence: EVM, operations: 'Once per string.', failure_modes: 'Plug not released, plug not bumping, head leaks.' } });
cm({ id: 'CM-CEMENTUNIT', parent: 'CM', group: 'cementing', level: 'equipment', name: 'Cementing unit and bulk equipment', aliases: ['cement unit', 'cement pump truck', 'bulk truck', 'batch mixer'],
  function: 'The pump truck that mixes and pumps the slurry, with the bulk cement transports and the batch mixer or recirculating mixer that feeds it.',
  tabs: { overview: 'Dry cement and additives are blended in bulk, mixed with water at the unit to the design density, and pumped down the casing at the planned rate; displacement follows with mud or water. Density and rate are recorded through the job.', engineering: 'Pump pressure for the job; densitometer control; slurry tests per API 10A before the job.', connections: 'Bulk to mixer to pump to the cement head.', safety: 'Cement dust and caustic slurry; high-pressure lines.', evidence: EVM, operations: 'Once per string; results feed the cement evaluation.', failure_modes: 'Density off target, pump failures, early set.' }, hazards: [H.cement, H.pressure] });
cm({ id: 'CM-CEMENTEVAL', parent: 'CM', group: 'evaluation', level: 'equipment', name: 'Cement evaluation (bond log)', aliases: ['cement bond log', 'CBL', 'VDL', 'ultrasonic cement evaluation', 'temperature survey'],
  function: 'The logs run inside the casing after the cement sets that estimate where the cement is and how well it bonds to the pipe and the formation.',
  tabs: { overview: 'A sonic tool measures how much the casing rings; well-bonded pipe rings less. Ultrasonic tools map the bond around the pipe. A temperature survey finds the top of cement from the heat of hydration. The completion uses the result to decide whether stages will be isolated behind pipe.', engineering: 'Run on wireline after the cement sets; interpretation depends on the cement and the casing.', connections: 'Run through the wellhead with a wireline unit (WL).', safety: 'Wireline hazards.', evidence: EVM, operations: 'Before the frac when isolation matters.', failure_modes: 'Ambiguous logs, microannulus, foam cement effects.' } });
cm({ id: 'CM-CASINGCONNECTION', parent: 'CM', group: 'wellbore', level: 'component', name: 'Casing connections', aliases: ['casing connection', 'threaded connection', 'premium connection', 'buttress', 'LTC'],
  function: 'The threaded joints between casing joints that carry the tension, seal the pressure, and survive the frac pressure cycles.',
  tabs: { overview: 'API connections (short and long round thread, buttress) and proprietary premium connections with metal seals; frac wells often use semi-premium or premium threads on the production string because of the pressure cycling.', engineering: 'Per API 5CT for API threads; make-up torque and thread compound per the connection.', safety: 'Make-up with power tongs; pinch points.', evidence: EVM }, drawn_in_3d: false, hazards: [H.pinch] });

// production tree record in WH points at the UC model
{
  const r = load('WH', 'WH-PRODUCTIONTREE');
  r.drawn_in_3d = true; r.glb = UC_GLB;
  r.mesh_nodes = ['UC-PRODTREE-TUBINGHEADADAPTER', 'UC-PRODTREE-LMV', 'UC-PRODTREE-UMV', 'UC-PRODTREE-FLOWCROSS', 'UC-PRODTREE-WINGVALVE', 'UC-PRODTREE-CHOKE', 'UC-PRODTREE-ACTUATOR', 'UC-PRODTREE-FLOWLINE', 'UC-PRODTREE-KILLWING', 'UC-PRODTREE-GAUGE', 'UC-PRODTREE-SWAB', 'UC-PRODTREE-TREECAP', 'UC-PRODTREE-STUDS'];
  r.tabs.overview = (r.tabs.overview || '') + '\n\nThe full record with components lives in the UC system as UC-PRODTREE; this entry keeps the wellhead system\'s view of the tree.';
  r.connections = [...(r.connections || []), { target: 'UC-PRODTREE', direction: 'undirected', type: 'mechanical', note: 'Component records' }];
  r.revision = rev('Drop 6: bound to the production tree model'); save(r);
}
console.log('Drop 6 seed done');
